unit FVoltarPedidoParaOriginal;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, StdCtrls, Mask, rxToolEdit, rxCurrEdit, Buttons, DB, ADODB;

type
  TVoltarPedidoParaOriginal = class(TForm)
    edtNumPed: TCurrencyEdit;
    lbl1: TLabel;
    btnConfirmar: TBitBtn;
    CadE120Ped: TADOQuery;
    CadE120PedCODEMP: TIntegerField;
    CadE120PedCODFIL: TIntegerField;
    CadE120PedNUMPED: TIntegerField;
    CadE120PedTIPPED: TIntegerField;
    CadE120PedPRCPED: TIntegerField;
    CadE120PedTNSPRO: TStringField;
    CadE120PedTNSSER: TStringField;
    CadE120PedDATEMI: TDateTimeField;
    CadE120PedHOREMI: TIntegerField;
    CadE120PedDATPRV: TDateTimeField;
    CadE120PedHORPRV: TIntegerField;
    CadE120PedOBSPED: TStringField;
    CadE120PedCODCLI: TIntegerField;
    CadE120PedCATCLI: TIntegerField;
    CadE120PedQTDVPF: TIntegerField;
    CadE120PedQTDMFP: TIntegerField;
    CadE120PedINDAGR: TStringField;
    CadE120PedSEQENT: TIntegerField;
    CadE120PedSEQCOB: TIntegerField;
    CadE120PedSEQCTO: TIntegerField;
    CadE120PedPEDCLI: TStringField;
    CadE120PedCODROE: TStringField;
    CadE120PedSEQROE: TIntegerField;
    CadE120PedCODREP: TIntegerField;
    CadE120PedCODMOE: TStringField;
    CadE120PedCODMCP: TStringField;
    CadE120PedDATMFP: TDateTimeField;
    CadE120PedCOTMFP: TFMTBCDField;
    CadE120PedDATMOE: TDateTimeField;
    CadE120PedCOTMOE: TFMTBCDField;
    CadE120PedFECMOE: TStringField;
    CadE120PedCODFCR: TStringField;
    CadE120PedDATFCR: TDateTimeField;
    CadE120PedCODCPG: TStringField;
    CadE120PedPGTANT: TStringField;
    CadE120PedCODFPG: TIntegerField;
    CadE120PedQTDABE: TFMTBCDField;
    CadE120PedQTDAEN: TFMTBCDField;
    CadE120PedCODTRA: TIntegerField;
    CadE120PedCODRED: TIntegerField;
    CadE120PedCODVIA: TStringField;
    CadE120PedPLAVEI: TStringField;
    CadE120PedVLRFUM: TBCDField;
    CadE120PedQTDFRE: TFMTBCDField;
    CadE120PedFORFRE: TIntegerField;
    CadE120PedVLRFRE: TBCDField;
    CadE120PedCIFFOB: TStringField;
    CadE120PedVLRSEG: TBCDField;
    CadE120PedVLREMB: TBCDField;
    CadE120PedVLRENC: TBCDField;
    CadE120PedVLROUT: TBCDField;
    CadE120PedVLRDAR: TBCDField;
    CadE120PedVLRFRD: TBCDField;
    CadE120PedVLROUD: TBCDField;
    CadE120PedPERDS1: TBCDField;
    CadE120PedPERDS2: TBCDField;
    CadE120PedPERDS3: TBCDField;
    CadE120PedPERDS4: TBCDField;
    CadE120PedVLRBPR: TBCDField;
    CadE120PedVLRDPR: TBCDField;
    CadE120PedVLRBSE: TBCDField;
    CadE120PedVLRDSE: TBCDField;
    CadE120PedVLRDS1: TBCDField;
    CadE120PedVLRDS2: TBCDField;
    CadE120PedVLRDS3: TBCDField;
    CadE120PedVLRDS4: TBCDField;
    CadE120PedVLROFE: TBCDField;
    CadE120PedVLRDZF: TBCDField;
    CadE120PedVLRBIP: TBCDField;
    CadE120PedVLRIPI: TBCDField;
    CadE120PedVLRBIC: TBCDField;
    CadE120PedVLRICM: TBCDField;
    CadE120PedVLRBSI: TBCDField;
    CadE120PedVLRSIC: TBCDField;
    CadE120PedVLRBSP: TBCDField;
    CadE120PedVLRSTP: TBCDField;
    CadE120PedVLRBSC: TBCDField;
    CadE120PedVLRSTC: TBCDField;
    CadE120PedVLRBIS: TBCDField;
    CadE120PedVLRISS: TBCDField;
    CadE120PedVLRBIR: TBCDField;
    CadE120PedVLRIRF: TBCDField;
    CadE120PedVLRBIN: TBCDField;
    CadE120PedVLRINS: TBCDField;
    CadE120PedVLRBCO: TBCDField;
    CadE120PedVLRCOM: TBCDField;
    CadE120PedVLRLPR: TBCDField;
    CadE120PedVLRLSE: TBCDField;
    CadE120PedVLRLOU: TBCDField;
    CadE120PedVLRLIQ: TBCDField;
    CadE120PedVLRFIN: TBCDField;
    CadE120PedVLRADT: TBCDField;
    CadE120PedQTDORI: TFMTBCDField;
    CadE120PedVLRORI: TBCDField;
    CadE120PedTEMPAR: TStringField;
    CadE120PedCODPOR: TStringField;
    CadE120PedCODCRT: TStringField;
    CadE120PedSITPED: TIntegerField;
    CadE120PedCODMOT: TIntegerField;
    CadE120PedOBSMOT: TStringField;
    CadE120PedPEDBLO: TStringField;
    CadE120PedUSUBLO: TBCDField;
    CadE120PedDATBLO: TDateTimeField;
    CadE120PedHORBLO: TIntegerField;
    CadE120PedINDSIG: TStringField;
    CadE120PedVERCAL: TIntegerField;
    CadE120PedHORINI: TIntegerField;
    CadE120PedHORFIM: TIntegerField;
    CadE120PedUSUGER: TBCDField;
    CadE120PedDATGER: TDateTimeField;
    CadE120PedHORGER: TIntegerField;
    CadE120PedPERFRE: TBCDField;
    CadE120PedPERSEG: TBCDField;
    CadE120PedPEREMB: TBCDField;
    CadE120PedPERENC: TBCDField;
    CadE120PedPEROUT: TBCDField;
    CadE120PedCODSAC: TBCDField;
    CadE120PedCODOPE: TIntegerField;
    CadE120PedCODVEN: TIntegerField;
    CadE120PedPEDPAL: TIntegerField;
    CadE120PedACEPAR: TStringField;
    CadE120PedPEROF1: TBCDField;
    CadE120PedPEROF2: TBCDField;
    CadE120PedUSUFEC: TBCDField;
    CadE120PedDATFEC: TDateTimeField;
    CadE120PedHORFEC: TIntegerField;
    CadE120PedCLIREL: TIntegerField;
    CadE120PedVLRBCL: TBCDField;
    CadE120PedVLRCSL: TBCDField;
    CadE120PedVLRBPT: TBCDField;
    CadE120PedVLRPIT: TBCDField;
    CadE120PedVLRBCT: TBCDField;
    CadE120PedVLRCRT: TBCDField;
    CadE120PedVLRBOR: TBCDField;
    CadE120PedVLROUR: TBCDField;
    CadE120PedCODMAR: TStringField;
    CadE120PedCODSRO: TStringField;
    CadE120PedFILFAT: TIntegerField;
    CadE120PedCODCDI: TIntegerField;
    CadE120PedCODLIP: TStringField;
    CadE120PedCEPFRE: TIntegerField;
    CadE120PedVLRRIS: TBCDField;
    CadE120PedANAEMB: TStringField;
    CadE120PedNUMEMP: TStringField;
    CadE120PedQTDANE: TIntegerField;
    CadE120PedDATAGE: TDateTimeField;
    CadE120PedFILNCO: TIntegerField;
    CadE120PedSNFNCO: TStringField;
    CadE120PedNUMNCO: TIntegerField;
    CadE120PedEXPWMS: TIntegerField;
    CadE120PedVLRBPF: TBCDField;
    CadE120PedVLRPIF: TBCDField;
    CadE120PedVLRBCF: TBCDField;
    CadE120PedVLRCFF: TBCDField;
    CadE120PedCODAPC: TIntegerField;
    CadE120PedSOMFRE: TStringField;
    CadE120PedQTDITP: TIntegerField;
    CadE120PedQTDITS: TIntegerField;
    CadE120PedPERDS5: TBCDField;
    CadE120PedVLRDS5: TBCDField;
    CadE120PedROTANX: TIntegerField;
    CadE120PedNUMANX: TBCDField;
    CadE120PedNUMNSU: TBCDField;
    CadE120PedDATNSU: TDateTimeField;
    CadE120PedHORNSU: TIntegerField;
    CadE120PedINDEXP: TIntegerField;
    CadE120PedFATPED: TIntegerField;
    CadE120PedQTDBPF: TBCDField;
    CadE120PedQTDBCF: TBCDField;
    CadE120PedQTDBIP: TBCDField;
    CadE120PedUSU_FILDIV: TIntegerField;
    CadE120PedUSU_PEDDIV: TIntegerField;
    CadE120PedUSU_USUDIV: TBCDField;
    CadE120PedUSU_DATDIV: TDateTimeField;
    CadE120PedUSU_HORDIV: TIntegerField;
    CadE120PedUSU_PEDTRA: TStringField;
    CadE120PedUSU_PRECAR: TIntegerField;
    CadE120PedUSU_USUDES: TBCDField;
    CadE120PedUSU_DATDES: TDateTimeField;
    CadE120PedUSU_HORDES: TIntegerField;
    CadE120PedUSU_NUMCOM: TIntegerField;
    CadE120PedNUMCES: TBCDField;
    CadE120PedVENCAL: TStringField;
    CadE120PedDESDEF: TStringField;
    CadE120PedANOVEI: TStringField;
    CadE120PedNUMREN: TStringField;
    CadE120PedDESMOD: TStringField;
    CadE120PedTIPDAV: TIntegerField;
    CadE120PedVLRECF: TBCDField;
    CadE120PedPERECF: TBCDField;
    CadE120PedTEMAVA: TStringField;
    CadUsu120Ipd: TADOQuery;
    CadUsu120IpdUSU_CODEMP: TIntegerField;
    CadUsu120IpdUSU_CODFIL: TIntegerField;
    CadUsu120IpdUSU_NUMPED: TIntegerField;
    CadUsu120IpdUSU_SEQIPD: TIntegerField;
    CadUsu120IpdUSU_QTDCOR: TIntegerField;
    CadUsu120IpdUSU_TIPCMB: TIntegerField;
    CadUsu120IpdUSU_COR001: TStringField;
    CadUsu120IpdUSU_COR002: TStringField;
    CadUsu120IpdUSU_SEQITE: TIntegerField;
    CadUsu120IpdUSU_CODPRO: TStringField;
    CadUsu120IpdUSU_CODDER: TStringField;
    CadUsu120IpdUSU_TECTRA: TStringField;
    CadUsu120IpdUSU_QTDABE: TIntegerField;
    CadUsu120IpdUSU_QTDCAN: TIntegerField;
    CadUsu120IpdUSU_NUMANE: TBCDField;
    CadUsu120IpdUSU_PRECAR: TIntegerField;
    CadUsu120IpdUSU_NUMCOM: TIntegerField;
    CadE120Ipd: TADOQuery;
    CadE120IpdCODEMP: TIntegerField;
    CadE120IpdCODFIL: TIntegerField;
    CadE120IpdNUMPED: TIntegerField;
    CadE120IpdSEQIPD: TIntegerField;
    CadE120IpdTNSPRO: TStringField;
    CadE120IpdPEDCLI: TStringField;
    CadE120IpdSEQPCL: TStringField;
    CadE120IpdPEDPRV: TStringField;
    CadE120IpdCODPRO: TStringField;
    CadE120IpdCODDER: TStringField;
    CadE120IpdCPLIPD: TStringField;
    CadE120IpdCODFAM: TStringField;
    CadE120IpdCODAGR: TIntegerField;
    CadE120IpdCODTIC: TStringField;
    CadE120IpdCODTRD: TStringField;
    CadE120IpdCODTST: TStringField;
    CadE120IpdCODSTP: TStringField;
    CadE120IpdCODSTC: TStringField;
    CadE120IpdCODDEP: TStringField;
    CadE120IpdCODLOT: TStringField;
    CadE120IpdRESEST: TStringField;
    CadE120IpdQTDPED: TFMTBCDField;
    CadE120IpdQTDAEN: TFMTBCDField;
    CadE120IpdQTDPOC: TFMTBCDField;
    CadE120IpdQTDFAT: TFMTBCDField;
    CadE120IpdQTDCAN: TFMTBCDField;
    CadE120IpdQTDABE: TFMTBCDField;
    CadE120IpdQTDRAE: TFMTBCDField;
    CadE120IpdQTDNLP: TFMTBCDField;
    CadE120IpdQTDRES: TFMTBCDField;
    CadE120IpdUNIMED: TStringField;
    CadE120IpdCODMCP: TStringField;
    CadE120IpdDATMFP: TDateTimeField;
    CadE120IpdCOTMFP: TFMTBCDField;
    CadE120IpdDATMOE: TDateTimeField;
    CadE120IpdCOTMOE: TFMTBCDField;
    CadE120IpdFECMOE: TStringField;
    CadE120IpdCODTPR: TStringField;
    CadE120IpdPREUNI: TFMTBCDField;
    CadE120IpdCODMOE: TStringField;
    CadE120IpdPREFIX: TStringField;
    CadE120IpdPERDSC: TBCDField;
    CadE120IpdPEROFE: TBCDField;
    CadE120IpdPERACR: TBCDField;
    CadE120IpdPERIPI: TBCDField;
    CadE120IpdPERICM: TBCDField;
    CadE120IpdPERCOM: TBCDField;
    CadE120IpdDATENT: TDateTimeField;
    CadE120IpdDATANE: TDateTimeField;
    CadE120IpdDATPOC: TDateTimeField;
    CadE120IpdCODPVP: TStringField;
    CadE120IpdNUMPRJ: TIntegerField;
    CadE120IpdCODFPJ: TIntegerField;
    CadE120IpdCTAFIN: TIntegerField;
    CadE120IpdCTARED: TIntegerField;
    CadE120IpdCODCCU: TStringField;
    CadE120IpdVLRFRE: TBCDField;
    CadE120IpdVLRSEG: TBCDField;
    CadE120IpdVLREMB: TBCDField;
    CadE120IpdVLRENC: TBCDField;
    CadE120IpdVLROUT: TBCDField;
    CadE120IpdVLRDAR: TBCDField;
    CadE120IpdVLRFRD: TBCDField;
    CadE120IpdVLROUD: TBCDField;
    CadE120IpdVLRBRU: TBCDField;
    CadE120IpdVLRDSC: TBCDField;
    CadE120IpdVLRDS1: TBCDField;
    CadE120IpdVLRDS2: TBCDField;
    CadE120IpdVLRDS3: TBCDField;
    CadE120IpdVLRDS4: TBCDField;
    CadE120IpdVLROFE: TBCDField;
    CadE120IpdVLRDZF: TBCDField;
    CadE120IpdVLRBIP: TBCDField;
    CadE120IpdVLRIPI: TBCDField;
    CadE120IpdVLRBIC: TBCDField;
    CadE120IpdVLRICM: TBCDField;
    CadE120IpdVLRBSI: TBCDField;
    CadE120IpdVLRICS: TBCDField;
    CadE120IpdVLRBSP: TBCDField;
    CadE120IpdVLRSTP: TBCDField;
    CadE120IpdVLRBSC: TBCDField;
    CadE120IpdVLRSTC: TBCDField;
    CadE120IpdVLRBCO: TBCDField;
    CadE120IpdVLRCOM: TBCDField;
    CadE120IpdVLRLPR: TBCDField;
    CadE120IpdVLRLOU: TBCDField;
    CadE120IpdVLRLIQ: TBCDField;
    CadE120IpdVLRFIN: TBCDField;
    CadE120IpdSITIPD: TIntegerField;
    CadE120IpdCODMOT: TIntegerField;
    CadE120IpdOBSMOT: TStringField;
    CadE120IpdGERNEC: TIntegerField;
    CadE120IpdGERCGA: TStringField;
    CadE120IpdRESMAN: TStringField;
    CadE120IpdINDAED: TStringField;
    CadE120IpdNUMCTR: TIntegerField;
    CadE120IpdDATCPT: TDateTimeField;
    CadE120IpdSEQCVP: TIntegerField;
    CadE120IpdUSUGER: TBCDField;
    CadE120IpdDATGER: TDateTimeField;
    CadE120IpdHORGER: TIntegerField;
    CadE120IpdQTDPPF: TFMTBCDField;
    CadE120IpdCMPKIT: TStringField;
    CadE120IpdFILOCP: TIntegerField;
    CadE120IpdNUMOCP: TIntegerField;
    CadE120IpdSEQIPO: TIntegerField;
    CadE120IpdUNIVEN: TStringField;
    CadE120IpdQTDVEN: TFMTBCDField;
    CadE120IpdPREVEN: TFMTBCDField;
    CadE120IpdPREBRU: TFMTBCDField;
    CadE120IpdFILCTR: TIntegerField;
    CadE120IpdCTRCVS: TIntegerField;
    CadE120IpdCPTCVS: TDateTimeField;
    CadE120IpdSEQCVS: TIntegerField;
    CadE120IpdCODAVC: TIntegerField;
    CadE120IpdCODFXA: TStringField;
    CadE120IpdCODPGR: TStringField;
    CadE120IpdIDXGRD: TIntegerField;
    CadE120IpdCODMAR: TStringField;
    CadE120IpdCODCLC: TStringField;
    CadE120IpdPERDS1: TBCDField;
    CadE120IpdPERDS2: TBCDField;
    CadE120IpdPERDS3: TBCDField;
    CadE120IpdPERDS4: TBCDField;
    CadE120IpdFILPRD: TIntegerField;
    CadE120IpdVLRRIS: TBCDField;
    CadE120IpdINDPCE: TStringField;
    CadE120IpdINDPCR: TStringField;
    CadE120IpdPERPIT: TBCDField;
    CadE120IpdVLRBPT: TBCDField;
    CadE120IpdVLRPIT: TBCDField;
    CadE120IpdPERCRT: TBCDField;
    CadE120IpdVLRBCT: TBCDField;
    CadE120IpdVLRCRT: TBCDField;
    CadE120IpdPERCSL: TBCDField;
    CadE120IpdVLRBCL: TBCDField;
    CadE120IpdVLRCSL: TBCDField;
    CadE120IpdPEROUR: TBCDField;
    CadE120IpdVLRBOR: TBCDField;
    CadE120IpdVLROUR: TBCDField;
    CadE120IpdPERIRF: TBCDField;
    CadE120IpdVLRBIR: TBCDField;
    CadE120IpdVLRIRF: TBCDField;
    CadE120IpdFILNFC: TIntegerField;
    CadE120IpdFORNFC: TIntegerField;
    CadE120IpdNUMNFC: TIntegerField;
    CadE120IpdSNFNFC: TStringField;
    CadE120IpdSEQIPC: TIntegerField;
    CadE120IpdNCTLCL: TStringField;
    CadE120IpdNRECLI: TStringField;
    CadE120IpdNOSICL: TBCDField;
    CadE120IpdNOSFCL: TBCDField;
    CadE120IpdNOCCL1: TStringField;
    CadE120IpdNOCCL2: TStringField;
    CadE120IpdNOCCL3: TStringField;
    CadE120IpdCODAGC: TStringField;
    CadE120IpdCTRCVP: TIntegerField;
    CadE120IpdCPTCVP: TDateTimeField;
    CadE120IpdSEQCTR: TIntegerField;
    CadE120IpdINDAPE: TIntegerField;
    CadE120IpdOBSIPD: TStringField;
    CadE120IpdSEQISP: TIntegerField;
    CadE120IpdEMPOCP: TIntegerField;
    CadE120IpdVLRBPF: TBCDField;
    CadE120IpdPERPIF: TBCDField;
    CadE120IpdVLRPIF: TBCDField;
    CadE120IpdVLRBCF: TBCDField;
    CadE120IpdPERCFF: TBCDField;
    CadE120IpdVLRCFF: TBCDField;
    CadE120IpdPERDS5: TBCDField;
    CadE120IpdVLRDS5: TBCDField;
    CadE120IpdAGRNEC: TStringField;
    CadE120IpdAGRPAI: TStringField;
    CadE120IpdORIRES: TStringField;
    CadE120IpdQTDBPF: TBCDField;
    CadE120IpdALIPIF: TBCDField;
    CadE120IpdQTDBCF: TBCDField;
    CadE120IpdALICFF: TBCDField;
    CadE120IpdQTDBIP: TBCDField;
    CadE120IpdALIIPI: TBCDField;
    CadE120IpdINDIPM: TStringField;
    CadE120IpdFILREM: TIntegerField;
    CadE120IpdSNFREM: TStringField;
    CadE120IpdNFVREM: TIntegerField;
    CadE120IpdIPVREM: TIntegerField;
    CadE120IpdCODCNV: TIntegerField;
    CadE120IpdCODREP: TIntegerField;
    CadE120IpdUSU_TIPCMB: TIntegerField;
    CadE120IpdUSU_CODTEC1: TStringField;
    CadE120IpdUSU_CODTEC2: TStringField;
    CadE120IpdUSU_QTDREP: TIntegerField;
    CadE120IpdUSU_QTDDIV: TBCDField;
    CadE120IpdUSU_MEDLAR: TBCDField;
    CadE120IpdUSU_MEDCOM: TBCDField;
    CadE120IpdUSU_MEDALT: TBCDField;
    CadE120IpdUSU_PERDESC1: TBCDField;
    CadE120IpdUSU_PERDESC2: TBCDField;
    CadE120IpdUSU_PERDESC3: TBCDField;
    CadE120IpdUSU_PERDESC4: TBCDField;
    CadE120IpdUSU_PERDESC5: TBCDField;
    CadE120IpdUSU_PERDESC6: TBCDField;
    CadE120IpdUSU_CANAPR: TFMTBCDField;
    CadE120IpdUSU_TOTDSC: TBCDField;
    CadE120IpdUSU_TOTDSCORI: TBCDField;
    CadE120IpdUSU_VLRORI: TBCDField;
    CadE120IpdUSU_NUMCOM: TIntegerField;
    Sql: TADOQuery;
    procedure btnConfirmarClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  VoltarPedidoParaOriginal: TVoltarPedidoParaOriginal;

implementation

uses UDmOra;

{$R *.dfm}

procedure TVoltarPedidoParaOriginal.btnConfirmarClick(Sender: TObject);
begin
    CadE120Ped.Close;
    CadE120Ped.Parameters.ParamByName('CODEMP').Value := 1;
    CadE120Ped.Parameters.ParamByName('CODFIL').Value := 1;
    CadE120Ped.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
    CadE120Ped.Open;
    if not CadE120Ped.IsEmpty then
       begin
          //ATUALIZA AS CORES
          CadUsu120Ipd.Close;
          CadUsu120Ipd.Parameters.ParamByName('CODEMP').Value := CadE120PedCODEMP.Value;
          CadUsu120Ipd.Parameters.ParamByName('CODFIL').Value := CadE120PedCODFIL.Value;
          CadUsu120Ipd.Parameters.ParamByName('NUMPED').Value := CadE120PedNUMPED.Value;
          CadUsu120Ipd.Open;
          CadUsu120Ipd.First;
          while not CadUsu120Ipd.Eof do
             begin
               CadUsu120Ipd.Edit;
               CadUsu120IpdUSU_QTDABE.Value := CadUsu120IpdUSU_QTDCOR.Value;
               CadUsu120IpdUSU_QTDCAN.Value := 0;
               CadUsu120Ipd.Post;

               CadUsu120Ipd.Next;
             end;

          //ATUALIZA OS PRODUTOS
          CadE120Ipd.Close;
          CadE120Ipd.Parameters.ParamByName('CODEMP').Value := CadE120PedCODEMP.Value;
          CadE120Ipd.Parameters.ParamByName('CODFIL').Value := CadE120PedCODFIL.Value;
          CadE120Ipd.Parameters.ParamByName('NUMPED').Value := CadE120PedNUMPED.Value;
          CadE120Ipd.Open;
          CadE120Ipd.First;
          while not CadE120Ipd.Eof do
             begin
               CadE120Ipd.Edit;
               CadE120IpdSITIPD.Value := 1;
               CadE120IpdQTDABE.Value := CadE120IpdQTDPED.Value;
               CadE120IpdQTDCAN.AsFloat := 0;
               CadE120Ipd.Post;

               CadE120Ipd.Next;
             end;

          //ATUALIZA O PEDIDO
          CadE120Ped.Edit;
          CadE120PedSITPED.Value := 1;
          CadE120Ped.Post;

          Sql.Close;
          Sql.SQL.Clear;
          Sql.SQL.Add('DELETE FROM E120OBS WHERE CODEMP = 1 AND ');
          Sql.SQL.Add('                          CODFIL = 101 AND');
          Sql.SQL.Add('                          NUMPED = :NUMPED');
          Sql.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
          Sql.ExecSQL;

          Sql.Close;
          Sql.SQL.Clear;
          Sql.SQL.Add('DELETE FROM USU_T120IPD WHERE USU_CODEMP = 1 AND ');
          Sql.SQL.Add('                              USU_CODFIL = 101 AND');
          Sql.SQL.Add('                              USU_NUMPED = :NUMPED');
          Sql.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
          Sql.ExecSQL;

          Sql.Close;
          Sql.SQL.Clear;
          Sql.SQL.Add('DELETE FROM E120RAT WHERE CODEMP = 1 AND ');
          Sql.SQL.Add('                          CODFIL = 101 AND');
          Sql.SQL.Add('                          NUMPED = :NUMPED');
          Sql.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
          Sql.ExecSQL;

          Sql.Close;
          Sql.SQL.Clear;
          Sql.SQL.Add('DELETE FROM E120IPD WHERE CODEMP = 1 AND ');
          Sql.SQL.Add('                          CODFIL = 101 AND');
          Sql.SQL.Add('                          NUMPED = :NUMPED');
          Sql.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
          Sql.ExecSQL;

          Sql.Close;
          Sql.SQL.Clear;
          Sql.SQL.Add('DELETE FROM E120PED WHERE CODEMP = 1 AND ');
          Sql.SQL.Add('                          CODFIL = 101 AND');
          Sql.SQL.Add('                          NUMPED = :NUMPED');
          Sql.Parameters.ParamByName('NUMPED').Value := edtNumPed.Value;
          Sql.ExecSQL;


          Application.MessageBox('Pedido restaurado com sucesso,  Agora você deve ir até o Sapiens e RECALCULAR O PEDIDO','Confirmação',MB_ICONQUESTION+MB_OK);
       end;


end;

end.
