unit UDm2;

interface

uses
  SysUtils, Classes, DB, ADODB, DBClient, Dialogs, Provider;

type
  TDm2 = class(TDataModule)
    ConsE120ped: TADOQuery;
    ConsE120pedCODEMP: TIntegerField;
    ConsE120pedCODFIL: TIntegerField;
    ConsE120pedNUMPED: TIntegerField;
    ConsE120pedTIPPED: TIntegerField;
    ConsE120pedPRCPED: TIntegerField;
    ConsE120pedTNSPRO: TStringField;
    ConsE120pedTNSSER: TStringField;
    ConsE120pedDATEMI: TDateTimeField;
    ConsE120pedHOREMI: TIntegerField;
    ConsE120pedDATPRV: TDateTimeField;
    ConsE120pedHORPRV: TIntegerField;
    ConsE120pedOBSPED: TStringField;
    ConsE120pedCODCLI: TIntegerField;
    ConsE120pedCATCLI: TIntegerField;
    ConsE120pedQTDVPF: TIntegerField;
    ConsE120pedQTDMFP: TIntegerField;
    ConsE120pedINDAGR: TStringField;
    ConsE120pedSEQENT: TIntegerField;
    ConsE120pedSEQCOB: TIntegerField;
    ConsE120pedSEQCTO: TIntegerField;
    ConsE120pedPEDCLI: TStringField;
    ConsE120pedCODROE: TStringField;
    ConsE120pedSEQROE: TIntegerField;
    ConsE120pedCODREP: TIntegerField;
    ConsE120pedCODMOE: TStringField;
    ConsE120pedCODMCP: TStringField;
    ConsE120pedDATMFP: TDateTimeField;
    ConsE120pedCOTMFP: TBCDField;
    ConsE120pedDATMOE: TDateTimeField;
    ConsE120pedCOTMOE: TBCDField;
    ConsE120pedFECMOE: TStringField;
    ConsE120pedCODFCR: TStringField;
    ConsE120pedDATFCR: TDateTimeField;
    ConsE120pedCODCPG: TStringField;
    ConsE120pedPGTANT: TStringField;
    ConsE120pedCODFPG: TIntegerField;
    ConsE120pedQTDABE: TBCDField;
    ConsE120pedQTDAEN: TBCDField;
    ConsE120pedCODTRA: TIntegerField;
    ConsE120pedCODRED: TIntegerField;
    ConsE120pedCODVIA: TStringField;
    ConsE120pedPLAVEI: TStringField;
    ConsE120pedVLRFUM: TBCDField;
    ConsE120pedQTDFRE: TBCDField;
    ConsE120pedFORFRE: TIntegerField;
    ConsE120pedVLRFRE: TBCDField;
    ConsE120pedCIFFOB: TStringField;
    ConsE120pedVLRSEG: TBCDField;
    ConsE120pedVLREMB: TBCDField;
    ConsE120pedVLRENC: TBCDField;
    ConsE120pedVLROUT: TBCDField;
    ConsE120pedVLRDAR: TBCDField;
    ConsE120pedVLRFRD: TBCDField;
    ConsE120pedVLROUD: TBCDField;
    ConsE120pedPERDS1: TBCDField;
    ConsE120pedPERDS2: TBCDField;
    ConsE120pedPERDS3: TBCDField;
    ConsE120pedPERDS4: TBCDField;
    ConsE120pedVLRBPR: TBCDField;
    ConsE120pedVLRDPR: TBCDField;
    ConsE120pedVLRBSE: TBCDField;
    ConsE120pedVLRDSE: TBCDField;
    ConsE120pedVLRDS1: TBCDField;
    ConsE120pedVLRDS2: TBCDField;
    ConsE120pedVLRDS3: TBCDField;
    ConsE120pedVLRDS4: TBCDField;
    ConsE120pedVLROFE: TBCDField;
    ConsE120pedVLRDZF: TBCDField;
    ConsE120pedVLRBIP: TBCDField;
    ConsE120pedVLRIPI: TBCDField;
    ConsE120pedVLRBIC: TBCDField;
    ConsE120pedVLRICM: TBCDField;
    ConsE120pedVLRBSI: TBCDField;
    ConsE120pedVLRSIC: TBCDField;
    ConsE120pedVLRBSP: TBCDField;
    ConsE120pedVLRSTP: TBCDField;
    ConsE120pedVLRBSC: TBCDField;
    ConsE120pedVLRSTC: TBCDField;
    ConsE120pedVLRBIS: TBCDField;
    ConsE120pedVLRISS: TBCDField;
    ConsE120pedVLRBIR: TBCDField;
    ConsE120pedVLRIRF: TBCDField;
    ConsE120pedVLRBIN: TBCDField;
    ConsE120pedVLRINS: TBCDField;
    ConsE120pedVLRBCO: TBCDField;
    ConsE120pedVLRCOM: TBCDField;
    ConsE120pedVLRLPR: TBCDField;
    ConsE120pedVLRLSE: TBCDField;
    ConsE120pedVLRLOU: TBCDField;
    ConsE120pedVLRLIQ: TBCDField;
    ConsE120pedVLRFIN: TBCDField;
    ConsE120pedVLRADT: TBCDField;
    ConsE120pedQTDORI: TBCDField;
    ConsE120pedVLRORI: TBCDField;
    ConsE120pedTEMPAR: TStringField;
    ConsE120pedCODPOR: TStringField;
    ConsE120pedCODCRT: TStringField;
    ConsE120pedSITPED: TIntegerField;
    ConsE120pedCODMOT: TIntegerField;
    ConsE120pedOBSMOT: TStringField;
    ConsE120pedPEDBLO: TStringField;
    ConsE120pedUSUBLO: TBCDField;
    ConsE120pedDATBLO: TDateTimeField;
    ConsE120pedHORBLO: TIntegerField;
    ConsE120pedINDSIG: TStringField;
    ConsE120pedVERCAL: TIntegerField;
    ConsE120pedHORINI: TIntegerField;
    ConsE120pedHORFIM: TIntegerField;
    ConsE120pedUSUGER: TBCDField;
    ConsE120pedDATGER: TDateTimeField;
    ConsE120pedHORGER: TIntegerField;
    ConsE120pedPERFRE: TBCDField;
    ConsE120pedPERSEG: TBCDField;
    ConsE120pedPEREMB: TBCDField;
    ConsE120pedPERENC: TBCDField;
    ConsE120pedPEROUT: TBCDField;
    ConsE120pedCODSAC: TBCDField;
    ConsE120pedCODOPE: TIntegerField;
    ConsE120pedCODVEN: TIntegerField;
    ConsE120pedPEDPAL: TIntegerField;
    ConsE120pedACEPAR: TStringField;
    ConsE120pedPEROF1: TBCDField;
    ConsE120pedPEROF2: TBCDField;
    ConsE120pedUSUFEC: TBCDField;
    ConsE120pedDATFEC: TDateTimeField;
    ConsE120pedHORFEC: TIntegerField;
    ConsE120pedCLIREL: TIntegerField;
    ConsE120pedVLRBCL: TBCDField;
    ConsE120pedVLRCSL: TBCDField;
    ConsE120pedVLRBPT: TBCDField;
    ConsE120pedVLRPIT: TBCDField;
    ConsE120pedVLRBCT: TBCDField;
    ConsE120pedVLRCRT: TBCDField;
    ConsE120pedVLRBOR: TBCDField;
    ConsE120pedVLROUR: TBCDField;
    ConsE120pedCODMAR: TStringField;
    ConsE120pedCODSRO: TStringField;
    ConsE120pedFILFAT: TIntegerField;
    ConsE120pedCODCDI: TIntegerField;
    ConsE120pedCODLIP: TStringField;
    ConsE120pedCEPFRE: TIntegerField;
    ConsE120pedVLRRIS: TBCDField;
    ConsE120pedANAEMB: TStringField;
    ConsE120pedNUMEMP: TStringField;
    ConsE120pedQTDANE: TIntegerField;
    ConsE120pedDATAGE: TDateTimeField;
    ConsE120pedFILNCO: TIntegerField;
    ConsE120pedSNFNCO: TStringField;
    ConsE120pedNUMNCO: TIntegerField;
    ConsE120pedEXPWMS: TIntegerField;
    ConsE120pedVLRBPF: TBCDField;
    ConsE120pedVLRPIF: TBCDField;
    ConsE120pedVLRBCF: TBCDField;
    ConsE120pedVLRCFF: TBCDField;
    ConsE120pedCODAPC: TIntegerField;
    ConsE120pedSOMFRE: TStringField;
    ConsE120pedQTDITP: TIntegerField;
    ConsE120pedQTDITS: TIntegerField;
    ConsE120pedPERDS5: TBCDField;
    ConsE120pedVLRDS5: TBCDField;
    ConsE120pedROTANX: TIntegerField;
    ConsE120pedNUMANX: TBCDField;
    ConsE120pedUSU_FILDIV: TIntegerField;
    ConsE120pedUSU_PEDDIV: TIntegerField;
    ConsE120pedUSU_USUDIV: TBCDField;
    ConsE120pedUSU_DATDIV: TDateTimeField;
    ConsE120pedUSU_HORDIV: TIntegerField;
    ConsE120pedUSU_PEDTRA: TStringField;
    ConsE120pedUSU_PRECAR: TIntegerField;
    ConsE120pedUSU_USUDES: TBCDField;
    ConsE120pedUSU_DATDES: TDateTimeField;
    ConsE120pedUSU_HORDES: TIntegerField;
    ConsE085Cli: TADOQuery;
    ConsE085CliCODCLI: TIntegerField;
    ConsE085CliNOMCLI: TStringField;
    ConsE085CliAPECLI: TStringField;
    ConsE085CliMARCLI: TStringField;
    ConsE085CliSENCLI: TStringField;
    ConsE085CliTIPCLI: TStringField;
    ConsE085CliTIPMER: TStringField;
    ConsE085CliTIPEMC: TIntegerField;
    ConsE085CliCLICON: TStringField;
    ConsE085CliCODRAM: TStringField;
    ConsE085CliINSEST: TStringField;
    ConsE085CliINSMUN: TStringField;
    ConsE085CliCGCCPF: TBCDField;
    ConsE085CliCODGRE: TIntegerField;
    ConsE085CliZONFRA: TIntegerField;
    ConsE085CliCODSUF: TStringField;
    ConsE085CliENDCLI: TStringField;
    ConsE085CliCPLEND: TStringField;
    ConsE085CliCLIPRX: TStringField;
    ConsE085CliZIPCOD: TStringField;
    ConsE085CliCEPCLI: TIntegerField;
    ConsE085CliCEPINI: TIntegerField;
    ConsE085CliBAICLI: TStringField;
    ConsE085CliCIDCLI: TStringField;
    ConsE085CliSIGUFS: TStringField;
    ConsE085CliCODPAI: TStringField;
    ConsE085CliTEMENT: TStringField;
    ConsE085CliENDENT: TStringField;
    ConsE085CliCPLENT: TStringField;
    ConsE085CliCEPENT: TIntegerField;
    ConsE085CliINIENT: TIntegerField;
    ConsE085CliCIDENT: TStringField;
    ConsE085CliESTENT: TStringField;
    ConsE085CliINSENT: TStringField;
    ConsE085CliCGCENT: TBCDField;
    ConsE085CliTEMCOB: TStringField;
    ConsE085CliENDCOB: TStringField;
    ConsE085CliCPLCOB: TStringField;
    ConsE085CliCEPCOB: TIntegerField;
    ConsE085CliINICOB: TIntegerField;
    ConsE085CliCIDCOB: TStringField;
    ConsE085CliESTCOB: TStringField;
    ConsE085CliCGCCOB: TBCDField;
    ConsE085CliENTCOR: TStringField;
    ConsE085CliFONCLI: TStringField;
    ConsE085CliFONCL2: TStringField;
    ConsE085CliFONCL3: TStringField;
    ConsE085CliFONCL4: TStringField;
    ConsE085CliFONCL5: TStringField;
    ConsE085CliFAXCLI: TStringField;
    ConsE085CliCXAPST: TIntegerField;
    ConsE085CliINTNET: TStringField;
    ConsE085CliCODROE: TStringField;
    ConsE085CliSEQROE: TIntegerField;
    ConsE085CliCODFOR: TIntegerField;
    ConsE085CliCLIREP: TIntegerField;
    ConsE085CliCLITRA: TIntegerField;
    ConsE085CliUSUCAD: TBCDField;
    ConsE085CliDATCAD: TDateTimeField;
    ConsE085CliDATFIM: TDateTimeField;
    ConsE085CliHORCAD: TIntegerField;
    ConsE085CliHORFIM: TIntegerField;
    ConsE085CliDATVCT: TDateTimeField;
    ConsE085CliDATATU: TDateTimeField;
    ConsE085CliHORATU: TIntegerField;
    ConsE085CliUSUATU: TBCDField;
    ConsE085CliQTDATU: TIntegerField;
    ConsE085CliDATICV: TDateTimeField;
    ConsE085CliSITCLI: TStringField;
    ConsE085CliCODMOT: TIntegerField;
    ConsE085CliBLOCRE: TStringField;
    ConsE085CliOBSMOT: TStringField;
    ConsE085CliUSUMOT: TBCDField;
    ConsE085CliDATMOT: TDateTimeField;
    ConsE085CliHORMOT: TIntegerField;
    ConsE085CliUSUOPE: TBCDField;
    ConsE085CliCODAMA: TStringField;
    ConsE085CliCODSAB: TStringField;
    ConsE085CliCODGAL: TStringField;
    ConsE085CliTRIICM: TStringField;
    ConsE085CliTRIIPI: TStringField;
    ConsE085CliBAIENT: TStringField;
    ConsE085CliBAICOB: TStringField;
    ConsE085CliCLIFOR: TStringField;
    ConsE085CliIDECLI: TStringField;
    ConsE085CliTRIPIS: TStringField;
    ConsE085CliTRICOF: TStringField;
    ConsE085CliINDEXP: TIntegerField;
    ConsE085CliDATPAL: TDateTimeField;
    ConsE085CliHORPAL: TIntegerField;
    ConsE085CliRETCOF: TStringField;
    ConsE085CliRETCSL: TStringField;
    ConsE085CliRETPIS: TStringField;
    ConsE085CliRETOUR: TStringField;
    ConsE085CliCODSRO: TStringField;
    ConsE085CliDATSUF: TDateTimeField;
    ConsE085CliCEPFRE: TIntegerField;
    ConsE085CliCODPDV: TIntegerField;
    ConsE085CliDATPDV: TDateTimeField;
    ConsE085CliHORPDV: TIntegerField;
    ConsE085CliRETPRO: TStringField;
    ConsE085CliRETIRF: TStringField;
    ConsE085CliLIMRET: TStringField;
    ConsE085CliCODCNV: TIntegerField;
    ConsE085CliCALFUN: TStringField;
    ConsE085CliEENCLI: TStringField;
    ConsE085CliEENENT: TStringField;
    ConsE085CliEENCOB: TStringField;
    ConsE085CliPERAIN: TBCDField;
    ConsE085CliNENCLI: TStringField;
    ConsE085CliNENCOB: TStringField;
    ConsE085CliTIPACE: TIntegerField;
    ConsE085CliCODREP: TIntegerField;
    ConsE090Rep: TADOQuery;
    ConsE090RepCODREP: TIntegerField;
    ConsE090RepAPEREP: TStringField;
    ConsE090RepSENREP: TStringField;
    ConsE090RepTIPREP: TStringField;
    ConsE090RepINSEST: TStringField;
    ConsE090RepINSMUN: TStringField;
    ConsE090RepCGCCPF: TBCDField;
    ConsE090RepENDREP: TStringField;
    ConsE090RepCPLEND: TStringField;
    ConsE090RepZIPCOD: TStringField;
    ConsE090RepCEPREP: TIntegerField;
    ConsE090RepBAIREP: TStringField;
    ConsE090RepCIDREP: TStringField;
    ConsE090RepSIGUFS: TStringField;
    ConsE090RepFONREP: TStringField;
    ConsE090RepFONRE2: TStringField;
    ConsE090RepFONRE3: TStringField;
    ConsE090RepFAXREP: TStringField;
    ConsE090RepCXAPST: TIntegerField;
    ConsE090RepINTNET: TStringField;
    ConsE090RepDATCAD: TDateTimeField;
    ConsE090RepDATATU: TDateTimeField;
    ConsE090RepSITREP: TStringField;
    ConsE090RepQTDDEP: TIntegerField;
    ConsE090RepCALIRF: TStringField;
    ConsE090RepCALISS: TStringField;
    ConsE090RepCALINS: TStringField;
    ConsE090RepGERTIT: TStringField;
    ConsE090RepCODMOT: TIntegerField;
    ConsE090RepOBSMOT: TStringField;
    ConsE090RepUSUMOT: TBCDField;
    ConsE090RepDATMOT: TDateTimeField;
    ConsE090RepHORMOT: TIntegerField;
    ConsE090RepDATNAS: TDateTimeField;
    ConsE090RepNUMRGE: TStringField;
    ConsE090RepORGRGE: TStringField;
    ConsE090RepDATRGE: TDateTimeField;
    ConsE090RepREPCLI: TIntegerField;
    ConsE090RepREPFOR: TIntegerField;
    ConsE090RepINDEXP: TIntegerField;
    ConsE090RepDATPAL: TDateTimeField;
    ConsE090RepHORPAL: TIntegerField;
    ConsE090RepCODCDI: TIntegerField;
    ConsE090RepEENREP: TStringField;
    ConsE090RepHORATU: TIntegerField;
    ConsE090RepNENREP: TStringField;
    ConsE090RepUSUCAD: TBCDField;
    ConsE090RepHORCAD: TIntegerField;
    ConsE090RepUSUATU: TBCDField;
    ConsE028Cpg: TADOQuery;
    ConsE028CpgCODEMP: TIntegerField;
    ConsE028CpgCODCPG: TStringField;
    ConsE028CpgDESCPG: TStringField;
    ConsE028CpgABRCPG: TStringField;
    ConsE028CpgAPLCPG: TStringField;
    ConsE028CpgPGTANT: TStringField;
    ConsE028CpgDIAESP: TStringField;
    ConsE028CpgDIAME1: TIntegerField;
    ConsE028CpgDIAME2: TIntegerField;
    ConsE028CpgDIAME3: TIntegerField;
    ConsE028CpgDIASEM: TStringField;
    ConsE028CpgDIAMES: TStringField;
    ConsE028CpgPRZMED: TIntegerField;
    ConsE028CpgQTDPAR: TIntegerField;
    ConsE028CpgIPIPAR: TStringField;
    ConsE028CpgICMPAR: TStringField;
    ConsE028CpgSUBPAR: TStringField;
    ConsE028CpgFREPAR: TStringField;
    ConsE028CpgSEGPAR: TStringField;
    ConsE028CpgENCPAR: TStringField;
    ConsE028CpgEMBPAR: TStringField;
    ConsE028CpgOUTPAR: TStringField;
    ConsE028CpgDARPAR: TStringField;
    ConsE028CpgACRFIN: TBCDField;
    ConsE028CpgVENDSC: TBCDField;
    ConsE028CpgCPRDSC: TBCDField;
    ConsE028CpgPERDSC: TBCDField;
    ConsE028CpgPERCOM: TBCDField;
    ConsE028CpgREDCOM: TBCDField;
    ConsE028CpgTIPPAR: TIntegerField;
    ConsE028CpgSITCPG: TStringField;
    ConsE028CpgCODTPR: TStringField;
    ConsE028CpgFVECPG: TStringField;
    ConsE028CpgFVEDEC: TStringField;
    ConsE028CpgINDEXP: TIntegerField;
    ConsE028CpgDATPAL: TDateTimeField;
    ConsE028CpgHORPAL: TIntegerField;
    ConsE028CpgTIPINT: TIntegerField;
    ConsE028CpgCODPDV: TIntegerField;
    ConsE028CpgISSPAR: TStringField;
    ConsE028CpgDATGER: TDateTimeField;
    ConsE028CpgHORGER: TIntegerField;
    ConsE028CpgUSUGER: TBCDField;
    ConsE028CpgDATATU: TDateTimeField;
    ConsE028CpgHORATU: TIntegerField;
    ConsE028CpgUSUATU: TBCDField;
    ConsE028CpgPERENC: TBCDField;
    ConsE120Ipd: TADOQuery;
    ConsE120IpdCODEMP: TIntegerField;
    ConsE120IpdCODFIL: TIntegerField;
    ConsE120IpdNUMPED: TIntegerField;
    ConsE120IpdSEQIPD: TIntegerField;
    ConsE120IpdTNSPRO: TStringField;
    ConsE120IpdPEDCLI: TStringField;
    ConsE120IpdSEQPCL: TStringField;
    ConsE120IpdPEDPRV: TStringField;
    ConsE120IpdCODPRO: TStringField;
    ConsE120IpdCODDER: TStringField;
    ConsE120IpdCPLIPD: TStringField;
    ConsE120IpdCODFAM: TStringField;
    ConsE120IpdCODAGR: TIntegerField;
    ConsE120IpdCODTIC: TStringField;
    ConsE120IpdCODTRD: TStringField;
    ConsE120IpdCODTST: TStringField;
    ConsE120IpdCODSTP: TStringField;
    ConsE120IpdCODSTC: TStringField;
    ConsE120IpdCODDEP: TStringField;
    ConsE120IpdCODLOT: TStringField;
    ConsE120IpdRESEST: TStringField;
    ConsE120IpdQTDPED: TBCDField;
    ConsE120IpdQTDAEN: TBCDField;
    ConsE120IpdQTDPOC: TBCDField;
    ConsE120IpdQTDFAT: TBCDField;
    ConsE120IpdQTDCAN: TBCDField;
    ConsE120IpdQTDABE: TBCDField;
    ConsE120IpdQTDRAE: TBCDField;
    ConsE120IpdQTDNLP: TBCDField;
    ConsE120IpdQTDRES: TBCDField;
    ConsE120IpdUNIMED: TStringField;
    ConsE120IpdCODMCP: TStringField;
    ConsE120IpdDATMFP: TDateTimeField;
    ConsE120IpdCOTMFP: TBCDField;
    ConsE120IpdDATMOE: TDateTimeField;
    ConsE120IpdCOTMOE: TBCDField;
    ConsE120IpdFECMOE: TStringField;
    ConsE120IpdCODTPR: TStringField;
    ConsE120IpdPREUNI: TBCDField;
    ConsE120IpdCODMOE: TStringField;
    ConsE120IpdPREFIX: TStringField;
    ConsE120IpdPERDSC: TBCDField;
    ConsE120IpdPEROFE: TBCDField;
    ConsE120IpdPERACR: TBCDField;
    ConsE120IpdPERIPI: TBCDField;
    ConsE120IpdPERICM: TBCDField;
    ConsE120IpdPERCOM: TBCDField;
    ConsE120IpdDATENT: TDateTimeField;
    ConsE120IpdDATANE: TDateTimeField;
    ConsE120IpdDATPOC: TDateTimeField;
    ConsE120IpdCODPVP: TStringField;
    ConsE120IpdNUMPRJ: TIntegerField;
    ConsE120IpdCODFPJ: TIntegerField;
    ConsE120IpdCTAFIN: TIntegerField;
    ConsE120IpdCTARED: TIntegerField;
    ConsE120IpdCODCCU: TStringField;
    ConsE120IpdVLRFRE: TBCDField;
    ConsE120IpdVLRSEG: TBCDField;
    ConsE120IpdVLREMB: TBCDField;
    ConsE120IpdVLRENC: TBCDField;
    ConsE120IpdVLROUT: TBCDField;
    ConsE120IpdVLRDAR: TBCDField;
    ConsE120IpdVLRFRD: TBCDField;
    ConsE120IpdVLROUD: TBCDField;
    ConsE120IpdVLRBRU: TBCDField;
    ConsE120IpdVLRDSC: TBCDField;
    ConsE120IpdVLRDS1: TBCDField;
    ConsE120IpdVLRDS2: TBCDField;
    ConsE120IpdVLRDS3: TBCDField;
    ConsE120IpdVLRDS4: TBCDField;
    ConsE120IpdVLROFE: TBCDField;
    ConsE120IpdVLRDZF: TBCDField;
    ConsE120IpdVLRBIP: TBCDField;
    ConsE120IpdVLRIPI: TBCDField;
    ConsE120IpdVLRBIC: TBCDField;
    ConsE120IpdVLRICM: TBCDField;
    ConsE120IpdVLRBSI: TBCDField;
    ConsE120IpdVLRICS: TBCDField;
    ConsE120IpdVLRBSP: TBCDField;
    ConsE120IpdVLRSTP: TBCDField;
    ConsE120IpdVLRBSC: TBCDField;
    ConsE120IpdVLRSTC: TBCDField;
    ConsE120IpdVLRBCO: TBCDField;
    ConsE120IpdVLRCOM: TBCDField;
    ConsE120IpdVLRLPR: TBCDField;
    ConsE120IpdVLRLOU: TBCDField;
    ConsE120IpdVLRLIQ: TBCDField;
    ConsE120IpdVLRFIN: TBCDField;
    ConsE120IpdSITIPD: TIntegerField;
    ConsE120IpdCODMOT: TIntegerField;
    ConsE120IpdOBSMOT: TStringField;
    ConsE120IpdGERNEC: TIntegerField;
    ConsE120IpdGERCGA: TStringField;
    ConsE120IpdRESMAN: TStringField;
    ConsE120IpdINDAED: TStringField;
    ConsE120IpdNUMCTR: TIntegerField;
    ConsE120IpdDATCPT: TDateTimeField;
    ConsE120IpdSEQCVP: TIntegerField;
    ConsE120IpdUSUGER: TBCDField;
    ConsE120IpdDATGER: TDateTimeField;
    ConsE120IpdHORGER: TIntegerField;
    ConsE120IpdQTDPPF: TBCDField;
    ConsE120IpdCMPKIT: TStringField;
    ConsE120IpdFILOCP: TIntegerField;
    ConsE120IpdNUMOCP: TIntegerField;
    ConsE120IpdSEQIPO: TIntegerField;
    ConsE120IpdUNIVEN: TStringField;
    ConsE120IpdQTDVEN: TBCDField;
    ConsE120IpdPREVEN: TBCDField;
    ConsE120IpdPREBRU: TBCDField;
    ConsE120IpdFILCTR: TIntegerField;
    ConsE120IpdCTRCVS: TIntegerField;
    ConsE120IpdCPTCVS: TDateTimeField;
    ConsE120IpdSEQCVS: TIntegerField;
    ConsE120IpdCODAVC: TIntegerField;
    ConsE120IpdCODFXA: TStringField;
    ConsE120IpdCODPGR: TStringField;
    ConsE120IpdIDXGRD: TIntegerField;
    ConsE120IpdCODMAR: TStringField;
    ConsE120IpdCODCLC: TStringField;
    ConsE120IpdPERDS1: TBCDField;
    ConsE120IpdPERDS2: TBCDField;
    ConsE120IpdPERDS3: TBCDField;
    ConsE120IpdPERDS4: TBCDField;
    ConsE120IpdFILPRD: TIntegerField;
    ConsE120IpdVLRRIS: TBCDField;
    ConsE120IpdINDPCE: TStringField;
    ConsE120IpdINDPCR: TStringField;
    ConsE120IpdPERPIT: TBCDField;
    ConsE120IpdVLRBPT: TBCDField;
    ConsE120IpdVLRPIT: TBCDField;
    ConsE120IpdPERCRT: TBCDField;
    ConsE120IpdVLRBCT: TBCDField;
    ConsE120IpdVLRCRT: TBCDField;
    ConsE120IpdPERCSL: TBCDField;
    ConsE120IpdVLRBCL: TBCDField;
    ConsE120IpdVLRCSL: TBCDField;
    ConsE120IpdPEROUR: TBCDField;
    ConsE120IpdVLRBOR: TBCDField;
    ConsE120IpdVLROUR: TBCDField;
    ConsE120IpdPERIRF: TBCDField;
    ConsE120IpdVLRBIR: TBCDField;
    ConsE120IpdVLRIRF: TBCDField;
    ConsE120IpdFILNFC: TIntegerField;
    ConsE120IpdFORNFC: TIntegerField;
    ConsE120IpdNUMNFC: TIntegerField;
    ConsE120IpdSNFNFC: TStringField;
    ConsE120IpdSEQIPC: TIntegerField;
    ConsE120IpdNCTLCL: TStringField;
    ConsE120IpdNRECLI: TStringField;
    ConsE120IpdNOSICL: TBCDField;
    ConsE120IpdNOSFCL: TBCDField;
    ConsE120IpdNOCCL1: TStringField;
    ConsE120IpdNOCCL2: TStringField;
    ConsE120IpdNOCCL3: TStringField;
    ConsE120IpdCODAGC: TStringField;
    ConsE120IpdCTRCVP: TIntegerField;
    ConsE120IpdCPTCVP: TDateTimeField;
    ConsE120IpdSEQCTR: TIntegerField;
    ConsE120IpdINDAPE: TIntegerField;
    ConsE120IpdOBSIPD: TStringField;
    ConsE120IpdSEQISP: TIntegerField;
    ConsE120IpdEMPOCP: TIntegerField;
    ConsE120IpdVLRBPF: TBCDField;
    ConsE120IpdPERPIF: TBCDField;
    ConsE120IpdVLRPIF: TBCDField;
    ConsE120IpdVLRBCF: TBCDField;
    ConsE120IpdPERCFF: TBCDField;
    ConsE120IpdVLRCFF: TBCDField;
    ConsE120IpdPERDS5: TBCDField;
    ConsE120IpdVLRDS5: TBCDField;
    ConsE120IpdUSU_TIPCMB: TIntegerField;
    ConsE120IpdUSU_CODTEC1: TStringField;
    ConsE120IpdUSU_CODTEC2: TStringField;
    ConsE120IpdUSU_QTDREP: TIntegerField;
    ConsE120IpdUSU_QTDDIV: TBCDField;
    ConsE120IpdUSU_MEDLAR: TBCDField;
    ConsE120IpdUSU_MEDCOM: TBCDField;
    ConsE120IpdUSU_MEDALT: TBCDField;
    ConsE120IpdUSU_PERDESC1: TBCDField;
    ConsE120IpdUSU_PERDESC2: TBCDField;
    ConsE120IpdUSU_PERDESC3: TBCDField;
    ConsE120IpdUSU_PERDESC4: TBCDField;
    ConsE120IpdUSU_PERDESC5: TBCDField;
    ConsE120IpdUSU_PERDESC6: TBCDField;
    ConsE120IpdUSU_CANAPR: TBCDField;
    ConsE120IpdUSU_TOTDSC: TBCDField;
    ConsE120IpdUSU_TOTDSCORI: TBCDField;
    ConsE120IpdORIRES: TStringField;
    ConsE120IpdUSU_VLRORI: TBCDField;
    ConsE120IpdDESPRO: TStringField;
    ConsE120IpdDESDER: TStringField;
    ConsUsu_T120Ipd: TADOQuery;
    ConsUsu_T120IpdUSU_CODEMP: TIntegerField;
    ConsUsu_T120IpdUSU_CODFIL: TIntegerField;
    ConsUsu_T120IpdUSU_NUMPED: TIntegerField;
    ConsUsu_T120IpdUSU_SEQIPD: TIntegerField;
    ConsUsu_T120IpdUSU_QTDCOR: TIntegerField;
    ConsUsu_T120IpdUSU_TIPCMB: TIntegerField;
    ConsUsu_T120IpdUSU_COR001: TStringField;
    ConsUsu_T120IpdUSU_COR002: TStringField;
    ConsUsu_T120IpdUSU_SEQITE: TIntegerField;
    ConsUsu_T120IpdUSU_CODPRO: TStringField;
    ConsUsu_T120IpdUSU_CODDER: TStringField;
    ConsUsu_T120IpdUSU_TECTRA: TStringField;
    ConsUsu_T120IpdUSU_QTDABE: TIntegerField;
    ConsUsu_T120IpdUSU_QTDCAN: TIntegerField;
    ConsUsu_T120IpdUSU_NUMANE: TBCDField;
    ConsUsu_T120IpdUSU_PRECAR: TIntegerField;
    ADOUsuT000sis: TADOQuery;
    ADOUsuT000sisUSU_URLSRV: TStringField;
    ADOUsuT000sisUSU_BASQRY: TStringField;
    ADOUsuT000sisUSU_USUCAD: TBCDField;
    ADOUsuT000sisUSU_DATCAD: TDateTimeField;
    ADOUsuT000sisUSU_HORCAD: TIntegerField;
    ADOUsuT000sisUSU_CODEMP: TIntegerField;
    ADOUsuT000sisUSU_CODFIL: TIntegerField;
    ADOUsuT000sisUSU_USUATU: TBCDField;
    ADOUsuT000sisUSU_DATATU: TDateTimeField;
    ADOUsuT000sisUSU_HORATU: TIntegerField;
    CadUsu_T120Ipd: TADOQuery;
    CadUsu_T120IpdUSU_CODEMP: TIntegerField;
    CadUsu_T120IpdUSU_CODFIL: TIntegerField;
    CadUsu_T120IpdUSU_NUMPED: TIntegerField;
    CadUsu_T120IpdUSU_SEQIPD: TIntegerField;
    CadUsu_T120IpdUSU_QTDCOR: TIntegerField;
    CadUsu_T120IpdUSU_TIPCMB: TIntegerField;
    CadUsu_T120IpdUSU_COR001: TStringField;
    CadUsu_T120IpdUSU_COR002: TStringField;
    CadUsu_T120IpdUSU_SEQITE: TIntegerField;
    CadUsu_T120IpdUSU_CODPRO: TStringField;
    CadUsu_T120IpdUSU_CODDER: TStringField;
    CadUsu_T120IpdUSU_TECTRA: TStringField;
    CadUsu_T120IpdUSU_QTDABE: TIntegerField;
    CadUsu_T120IpdUSU_QTDCAN: TIntegerField;
    CadUsu_T120IpdUSU_NUMANE: TBCDField;
    CadUsu_T120IpdUSU_PRECAR: TIntegerField;
    ConsUsu_TDerCor: TADOQuery;
    ConsUsu_TDerCorUSU_CODEMP: TIntegerField;
    ConsUsu_TDerCorUSU_CODPRO: TStringField;
    ConsUsu_TDerCorUSU_CODDER: TStringField;
    ConsUsu_TDerCorUSU_CODTEC: TStringField;
    ConsUsu_TDerCorUSU_SITTEC: TStringField;
    ConsUsu_TDerCorUSU_DESTEC: TStringField;
    CadE120Ipd: TADOQuery;
    CadE120IpdCODEMP: TIntegerField;
    CadE120IpdCODFIL: TIntegerField;
    CadE120IpdNUMPED: TIntegerField;
    CadE120IpdSEQIPD: TIntegerField;
    CadE120IpdTNSPRO: TStringField;
    CadE120IpdPEDCLI: TStringField;
    CadE120IpdSEQPCL: TStringField;
    CadE120IpdPEDPRV: TStringField;
    CadE120IpdCODPRO: TStringField;
    CadE120IpdCODDER: TStringField;
    CadE120IpdCPLIPD: TStringField;
    CadE120IpdCODFAM: TStringField;
    CadE120IpdCODAGR: TIntegerField;
    CadE120IpdCODTIC: TStringField;
    CadE120IpdCODTRD: TStringField;
    CadE120IpdCODTST: TStringField;
    CadE120IpdCODSTP: TStringField;
    CadE120IpdCODSTC: TStringField;
    CadE120IpdCODDEP: TStringField;
    CadE120IpdCODLOT: TStringField;
    CadE120IpdRESEST: TStringField;
    CadE120IpdQTDPED: TBCDField;
    CadE120IpdQTDAEN: TBCDField;
    CadE120IpdQTDPOC: TBCDField;
    CadE120IpdQTDFAT: TBCDField;
    CadE120IpdQTDCAN: TBCDField;
    CadE120IpdQTDABE: TBCDField;
    CadE120IpdQTDRAE: TBCDField;
    CadE120IpdQTDNLP: TBCDField;
    CadE120IpdQTDRES: TBCDField;
    CadE120IpdUNIMED: TStringField;
    CadE120IpdCODMCP: TStringField;
    CadE120IpdDATMFP: TDateTimeField;
    CadE120IpdCOTMFP: TBCDField;
    CadE120IpdDATMOE: TDateTimeField;
    CadE120IpdCOTMOE: TBCDField;
    CadE120IpdFECMOE: TStringField;
    CadE120IpdCODTPR: TStringField;
    CadE120IpdPREUNI: TBCDField;
    CadE120IpdCODMOE: TStringField;
    CadE120IpdPREFIX: TStringField;
    CadE120IpdPERDSC: TBCDField;
    CadE120IpdPEROFE: TBCDField;
    CadE120IpdPERACR: TBCDField;
    CadE120IpdPERIPI: TBCDField;
    CadE120IpdPERICM: TBCDField;
    CadE120IpdPERCOM: TBCDField;
    CadE120IpdDATENT: TDateTimeField;
    CadE120IpdDATANE: TDateTimeField;
    CadE120IpdDATPOC: TDateTimeField;
    CadE120IpdCODPVP: TStringField;
    CadE120IpdNUMPRJ: TIntegerField;
    CadE120IpdCODFPJ: TIntegerField;
    CadE120IpdCTAFIN: TIntegerField;
    CadE120IpdCTARED: TIntegerField;
    CadE120IpdCODCCU: TStringField;
    CadE120IpdVLRFRE: TBCDField;
    CadE120IpdVLRSEG: TBCDField;
    CadE120IpdVLREMB: TBCDField;
    CadE120IpdVLRENC: TBCDField;
    CadE120IpdVLROUT: TBCDField;
    CadE120IpdVLRDAR: TBCDField;
    CadE120IpdVLRFRD: TBCDField;
    CadE120IpdVLROUD: TBCDField;
    CadE120IpdVLRBRU: TBCDField;
    CadE120IpdVLRDSC: TBCDField;
    CadE120IpdVLRDS1: TBCDField;
    CadE120IpdVLRDS2: TBCDField;
    CadE120IpdVLRDS3: TBCDField;
    CadE120IpdVLRDS4: TBCDField;
    CadE120IpdVLROFE: TBCDField;
    CadE120IpdVLRDZF: TBCDField;
    CadE120IpdVLRBIP: TBCDField;
    CadE120IpdVLRIPI: TBCDField;
    CadE120IpdVLRBIC: TBCDField;
    CadE120IpdVLRICM: TBCDField;
    CadE120IpdVLRBSI: TBCDField;
    CadE120IpdVLRICS: TBCDField;
    CadE120IpdVLRBSP: TBCDField;
    CadE120IpdVLRSTP: TBCDField;
    CadE120IpdVLRBSC: TBCDField;
    CadE120IpdVLRSTC: TBCDField;
    CadE120IpdVLRBCO: TBCDField;
    CadE120IpdVLRCOM: TBCDField;
    CadE120IpdVLRLPR: TBCDField;
    CadE120IpdVLRLOU: TBCDField;
    CadE120IpdVLRLIQ: TBCDField;
    CadE120IpdVLRFIN: TBCDField;
    CadE120IpdSITIPD: TIntegerField;
    CadE120IpdCODMOT: TIntegerField;
    CadE120IpdOBSMOT: TStringField;
    CadE120IpdGERNEC: TIntegerField;
    CadE120IpdGERCGA: TStringField;
    CadE120IpdRESMAN: TStringField;
    CadE120IpdINDAED: TStringField;
    CadE120IpdNUMCTR: TIntegerField;
    CadE120IpdDATCPT: TDateTimeField;
    CadE120IpdSEQCVP: TIntegerField;
    CadE120IpdUSUGER: TBCDField;
    CadE120IpdDATGER: TDateTimeField;
    CadE120IpdHORGER: TIntegerField;
    CadE120IpdQTDPPF: TBCDField;
    CadE120IpdCMPKIT: TStringField;
    CadE120IpdFILOCP: TIntegerField;
    CadE120IpdNUMOCP: TIntegerField;
    CadE120IpdSEQIPO: TIntegerField;
    CadE120IpdUNIVEN: TStringField;
    CadE120IpdQTDVEN: TBCDField;
    CadE120IpdPREVEN: TBCDField;
    CadE120IpdPREBRU: TBCDField;
    CadE120IpdFILCTR: TIntegerField;
    CadE120IpdCTRCVS: TIntegerField;
    CadE120IpdCPTCVS: TDateTimeField;
    CadE120IpdSEQCVS: TIntegerField;
    CadE120IpdCODAVC: TIntegerField;
    CadE120IpdCODFXA: TStringField;
    CadE120IpdCODPGR: TStringField;
    CadE120IpdIDXGRD: TIntegerField;
    CadE120IpdCODMAR: TStringField;
    CadE120IpdCODCLC: TStringField;
    CadE120IpdPERDS1: TBCDField;
    CadE120IpdPERDS2: TBCDField;
    CadE120IpdPERDS3: TBCDField;
    CadE120IpdPERDS4: TBCDField;
    CadE120IpdFILPRD: TIntegerField;
    CadE120IpdVLRRIS: TBCDField;
    CadE120IpdINDPCE: TStringField;
    CadE120IpdINDPCR: TStringField;
    CadE120IpdPERPIT: TBCDField;
    CadE120IpdVLRBPT: TBCDField;
    CadE120IpdVLRPIT: TBCDField;
    CadE120IpdPERCRT: TBCDField;
    CadE120IpdVLRBCT: TBCDField;
    CadE120IpdVLRCRT: TBCDField;
    CadE120IpdPERCSL: TBCDField;
    CadE120IpdVLRBCL: TBCDField;
    CadE120IpdVLRCSL: TBCDField;
    CadE120IpdPEROUR: TBCDField;
    CadE120IpdVLRBOR: TBCDField;
    CadE120IpdVLROUR: TBCDField;
    CadE120IpdPERIRF: TBCDField;
    CadE120IpdVLRBIR: TBCDField;
    CadE120IpdVLRIRF: TBCDField;
    CadE120IpdFILNFC: TIntegerField;
    CadE120IpdFORNFC: TIntegerField;
    CadE120IpdNUMNFC: TIntegerField;
    CadE120IpdSNFNFC: TStringField;
    CadE120IpdSEQIPC: TIntegerField;
    CadE120IpdNCTLCL: TStringField;
    CadE120IpdNRECLI: TStringField;
    CadE120IpdNOSICL: TBCDField;
    CadE120IpdNOSFCL: TBCDField;
    CadE120IpdNOCCL1: TStringField;
    CadE120IpdNOCCL2: TStringField;
    CadE120IpdNOCCL3: TStringField;
    CadE120IpdCODAGC: TStringField;
    CadE120IpdCTRCVP: TIntegerField;
    CadE120IpdCPTCVP: TDateTimeField;
    CadE120IpdSEQCTR: TIntegerField;
    CadE120IpdINDAPE: TIntegerField;
    CadE120IpdOBSIPD: TStringField;
    CadE120IpdSEQISP: TIntegerField;
    CadE120IpdEMPOCP: TIntegerField;
    CadE120IpdVLRBPF: TBCDField;
    CadE120IpdPERPIF: TBCDField;
    CadE120IpdVLRPIF: TBCDField;
    CadE120IpdVLRBCF: TBCDField;
    CadE120IpdPERCFF: TBCDField;
    CadE120IpdVLRCFF: TBCDField;
    CadE120IpdPERDS5: TBCDField;
    CadE120IpdVLRDS5: TBCDField;
    CadE120IpdUSU_TIPCMB: TIntegerField;
    CadE120IpdUSU_CODTEC1: TStringField;
    CadE120IpdUSU_CODTEC2: TStringField;
    CadE120IpdUSU_QTDREP: TIntegerField;
    CadE120IpdUSU_QTDDIV: TBCDField;
    CadE120IpdUSU_MEDLAR: TBCDField;
    CadE120IpdUSU_MEDCOM: TBCDField;
    CadE120IpdUSU_MEDALT: TBCDField;
    CadE120IpdUSU_PERDESC1: TBCDField;
    CadE120IpdUSU_PERDESC2: TBCDField;
    CadE120IpdUSU_PERDESC3: TBCDField;
    CadE120IpdUSU_PERDESC4: TBCDField;
    CadE120IpdUSU_PERDESC5: TBCDField;
    CadE120IpdUSU_PERDESC6: TBCDField;
    CadE120IpdUSU_CANAPR: TBCDField;
    CadE120IpdUSU_TOTDSC: TBCDField;
    CadE120IpdUSU_TOTDSCORI: TBCDField;
    CadE120IpdORIRES: TStringField;
    CadE120IpdUSU_VLRORI: TBCDField;
    ConsE210Mvp: TADOQuery;
    ConsE210MvpCODEMP: TIntegerField;
    ConsE210MvpCODPRO: TStringField;
    ConsE210MvpCODDER: TStringField;
    ConsE210MvpCODDEP: TStringField;
    ConsE210MvpDATMOV: TDateTimeField;
    ConsE210MvpSEQMOV: TIntegerField;
    ConsE210MvpDATFEC: TDateTimeField;
    ConsE210MvpSEQFEC: TIntegerField;
    ConsE210MvpFILDEP: TIntegerField;
    ConsE210MvpMSKDEP: TStringField;
    ConsE210MvpNIVDEP: TIntegerField;
    ConsE210MvpCODTNS: TStringField;
    ConsE210MvpESTMOV: TStringField;
    ConsE210MvpESTEOS: TStringField;
    ConsE210MvpESTVMV: TStringField;
    ConsE210MvpORIORP: TStringField;
    ConsE210MvpNUMDOC: TIntegerField;
    ConsE210MvpDATFAB: TDateTimeField;
    ConsE210MvpDATENT: TDateTimeField;
    ConsE210MvpDATVLT: TDateTimeField;
    ConsE210MvpCODLOT: TStringField;
    ConsE210MvpNUMSEP: TStringField;
    ConsE210MvpOBSMVP: TStringField;
    ConsE210MvpQTDMOV: TFMTBCDField;
    ConsE210MvpVLRMOV: TBCDField;
    ConsE210MvpQTDANT: TFMTBCDField;
    ConsE210MvpVLRANT: TBCDField;
    ConsE210MvpQTDEST: TFMTBCDField;
    ConsE210MvpVLREST: TBCDField;
    ConsE210MvpPRMEST: TFMTBCDField;
    ConsE210MvpPROTRF: TStringField;
    ConsE210MvpDERTRF: TStringField;
    ConsE210MvpDEPTRF: TStringField;
    ConsE210MvpSEQTRF: TIntegerField;
    ConsE210MvpUSURES: TBCDField;
    ConsE210MvpCODCCU: TStringField;
    ConsE210MvpUSUREC: TBCDField;
    ConsE210MvpCTARED: TIntegerField;
    ConsE210MvpNUMPRJ: TIntegerField;
    ConsE210MvpCODFPJ: TIntegerField;
    ConsE210MvpCTAFIN: TIntegerField;
    ConsE210MvpLCTFIN: TStringField;
    ConsE210MvpNUMLOT: TIntegerField;
    ConsE210MvpNUMEME: TIntegerField;
    ConsE210MvpSEQEME: TIntegerField;
    ConsE210MvpCODFIL: TIntegerField;
    ConsE210MvpCODSNF: TStringField;
    ConsE210MvpNUMNFV: TIntegerField;
    ConsE210MvpSEQIPV: TIntegerField;
    ConsE210MvpCODCLI: TIntegerField;
    ConsE210MvpFILOCP: TIntegerField;
    ConsE210MvpNUMOCP: TIntegerField;
    ConsE210MvpSEQIPO: TIntegerField;
    ConsE210MvpFILNFC: TIntegerField;
    ConsE210MvpCODFOR: TIntegerField;
    ConsE210MvpNUMNFC: TIntegerField;
    ConsE210MvpSNFNFC: TStringField;
    ConsE210MvpSEQIPC: TIntegerField;
    ConsE210MvpUSUDIG: TBCDField;
    ConsE210MvpDATDIG: TDateTimeField;
    ConsE210MvpHORDIG: TIntegerField;
    ConsE210MvpCODLIG: TIntegerField;
    ConsE210MvpMOTMVP: TStringField;
    ConsE210MvpDATINV: TDateTimeField;
    ConsE210MvpEXPWMS: TIntegerField;
    ConsE210MvpVLRDM1: TFMTBCDField;
    ConsE210MvpVLRDM2: TFMTBCDField;
    ConsE210MvpVLRDM3: TFMTBCDField;
    ConsE210MvpVLRDM4: TFMTBCDField;
    ConsE210MvpVLRDM5: TFMTBCDField;
    ConsE210MvpVLRDM6: TFMTBCDField;
    ConsE210MvpESTWMS: TStringField;
    ConsE210MvpESTCOC: TStringField;
    ConsE210MvpESTCOF: TStringField;
    ConsE210MvpFILPED: TIntegerField;
    ConsE210MvpNUMPED: TIntegerField;
    ConsE210MvpSEQIPD: TIntegerField;
    ConsE210MvpUTIREP: TStringField;
    ConsE210MvpFILANE: TIntegerField;
    ConsE210MvpNUMANE: TBCDField;
    ConsE210MvpNUMPFA: TIntegerField;
    ConsE210MvpSEQPES: TIntegerField;
    ConsE210MvpLOTDES: TStringField;
    ConsE210MvpCODETG: TIntegerField;
    ConsE210MvpSEQCMP: TIntegerField;
    ConsE210MvpACEFEC: TStringField;
    ConsE210MvpULTMDI: TStringField;
    ConsE210MvpCODBEM: TStringField;
    ConsE210MvpFILCLE: TIntegerField;
    ConsE210MvpNUMCLE: TIntegerField;
    ConsE210MvpVLRCM1: TBCDField;
    ConsE210MvpDATCM1: TDateTimeField;
    ConsE210MvpCOTCM1: TFMTBCDField;
    ConsE210MvpVLRCM2: TBCDField;
    ConsE210MvpDATCM2: TDateTimeField;
    ConsE210MvpCOTCM2: TFMTBCDField;
    ConsE210MvpSEPDES: TStringField;
    ConsE210MvpCODSLT: TStringField;
    ConsE210MvpPERGER: TBCDField;
    ConsE210MvpPERPUR: TBCDField;
    ConsE210MvpPERUMI: TBCDField;
    ConsE210MvpDATTES: TDateTimeField;
    ConsE210MvpCODEND: TStringField;
    ConsE210MvpCODSAF: TStringField;
    ConsE210MvpCODTRM: TStringField;
    ConsE210MvpCODBNF: TStringField;
    ConsE210MvpCODCAT: TStringField;
    ConsE210MvpAMONUM: TIntegerField;
    ConsE210MvpVLRICM: TBCDField;
    ConsE210MvpPRMICM: TFMTBCDField;
    ConsE210MvpICMACF: TBCDField;
    CadUsu_TSalCus: TADOQuery;
    CadUsu_TSalCusUSU_CODPRO: TStringField;
    CadUsu_TSalCusUSU_CODDER: TStringField;
    CadUsu_TSalCusUSU_QTDPRO: TIntegerField;
    CadUsu_TSalCusUSU_PREUNI: TBCDField;
    CadUsu_TSalCusUSU_PRETOT: TBCDField;
    ConsE081Itp: TADOQuery;
    ConsE081ItpCODEMP: TIntegerField;
    ConsE081ItpCODTPR: TStringField;
    ConsE081ItpDATINI: TDateTimeField;
    ConsE081ItpCODPRO: TStringField;
    ConsE081ItpCODDER: TStringField;
    ConsE081ItpQTDMAX: TBCDField;
    ConsE081ItpPREBAS: TFMTBCDField;
    ConsE081ItpPERDSC: TBCDField;
    ConsE081ItpPERLIM: TBCDField;
    ConsE081ItpPERCOM: TBCDField;
    ConsE081ItpTOLMAI: TBCDField;
    ConsE081ItpTOLMEN: TBCDField;
    ConsE081ItpSITREG: TStringField;
    ConsE081ItpINDEXC: TStringField;
    ConsE081ItpINDEXP: TIntegerField;
    ConsE081ItpDATPAL: TDateTimeField;
    ConsE081ItpHORPAL: TIntegerField;
    ConsE081ItpDATGER: TDateTimeField;
    ConsE081ItpHORGER: TIntegerField;
    ConsE081ItpUSUGER: TBCDField;
    ConsE081ItpDATALT: TDateTimeField;
    ConsE081ItpHORALT: TIntegerField;
    ConsE081ItpUSUALT: TBCDField;
    ConsE081ItpPROEXT: TStringField;
    ConsE081ItpPREMT2: TFMTBCDField;
    ConsE081ItpVLRCMO: TFMTBCDField;
    ConsE081ItpVLRCTE: TFMTBCDField;
    ConsE081ItpVLRCPR: TFMTBCDField;
    ConsE081ItpPREORC: TFMTBCDField;
    ConsE081ItpDATORC: TDateTimeField;
    ConsE081ItpCODREP: TIntegerField;
    ConsE081ItpCODPRB: TStringField;
    ConsE081ItpVLTMAI: TFMTBCDField;
    ConsE081ItpVLTMEN: TFMTBCDField;
    ConsE081ItpOBSITP: TStringField;
    ConsUsu_TSalCus: TADOQuery;
    ConsUsu_TSalCusUSU_CODPRO: TStringField;
    ConsUsu_TSalCusUSU_CODDER: TStringField;
    ConsUsu_TSalCusUSU_QTDPRO: TIntegerField;
    ConsUsu_TSalCusUSU_PREUNI: TBCDField;
    ConsUsu_TSalCusUSU_PRETOT: TBCDField;
    ConsUsu_TSalCusUSU_PERREP: TBCDField;
    CadUsu_TSalCusUSU_PERREP: TBCDField;
    ConsE210MvpMP: TADOQuery;
    ConsE210MvpMPVLRMOV: TBCDField;
    CadE075Der: TADOQuery;
    CadE075DerCODEMP: TIntegerField;
    CadE075DerCODPRO: TStringField;
    CadE075DerCODDER: TStringField;
    CadE075DerDESDER: TStringField;
    CadE075DerDESCPL: TStringField;
    CadE075DerCODBAR: TBCDField;
    CadE075DerCODAGR: TIntegerField;
    CadE075DerCODAGT: TStringField;
    CadE075DerSEQCMD: TIntegerField;
    CadE075DerDATVAL: TDateTimeField;
    CadE075DerDIAVLT: TIntegerField;
    CadE075DerTIPCN2: TStringField;
    CadE075DerVLRCN2: TFMTBCDField;
    CadE075DerTIPCN3: TStringField;
    CadE075DerVLRCN3: TFMTBCDField;
    CadE075DerPRECUS: TFMTBCDField;
    CadE075DerDATCUS: TDateTimeField;
    CadE075DerPREMED: TFMTBCDField;
    CadE075DerDATMED: TDateTimeField;
    CadE075DerPREUEN: TFMTBCDField;
    CadE075DerDATUEN: TDateTimeField;
    CadE075DerPREREP: TFMTBCDField;
    CadE075DerDATREP: TDateTimeField;
    CadE075DerDIAREP: TIntegerField;
    CadE075DerPESBRU: TFMTBCDField;
    CadE075DerPESLIQ: TFMTBCDField;
    CadE075DerTOLPES: TBCDField;
    CadE075DerVOLDER: TFMTBCDField;
    CadE075DerPERPRD: TBCDField;
    CadE075DerQTDIQL: TFMTBCDField;
    CadE075DerQTDCIC: TFMTBCDField;
    CadE075DerQTDPRD: TFMTBCDField;
    CadE075DerPREUIS: TFMTBCDField;
    CadE075DerPERICS: TBCDField;
    CadE075DerCODEMB: TIntegerField;
    CadE075DerCODROT: TStringField;
    CadE075DerCODROY: TIntegerField;
    CadE075DerBXAORP: TStringField;
    CadE075DerSERCCL: TStringField;
    CadE075DerNUMCCL: TStringField;
    CadE075DerCURABC: TStringField;
    CadE075DerCURAB2: TStringField;
    CadE075DerCURAB3: TStringField;
    CadE075DerCURAB4: TStringField;
    CadE075DerCODREG: TIntegerField;
    CadE075DerSITDER: TStringField;
    CadE075DerCODMOT: TIntegerField;
    CadE075DerCTRLOT: TStringField;
    CadE075DerCTRSEP: TStringField;
    CadE075DerCTRVLD: TStringField;
    CadE075DerDEPPAD: TStringField;
    CadE075DerDEPPAA: TStringField;
    CadE075DerINDPCE: TStringField;
    CadE075DerINDPCR: TStringField;
    CadE075DerINDKAN: TStringField;
    CadE075DerCODREF: TStringField;
    CadE075DerCODPIN: TStringField;
    CadE075DerNOTFOR: TBCDField;
    CadE075DerORICUS: TStringField;
    CadE075DerINFCUS: TStringField;
    CadE075DerHORCUS: TIntegerField;
    CadE075DerUSUGER: TBCDField;
    CadE075DerHORGER: TIntegerField;
    CadE075DerDATGER: TDateTimeField;
    CadE075DerUSUALT: TBCDField;
    CadE075DerHORALT: TIntegerField;
    CadE075DerDATALT: TDateTimeField;
    CadE075DerCODAGE: TStringField;
    CadE075DerCODBA2: TStringField;
    CadE075DerINDEXP: TIntegerField;
    CadE075DerDATPAL: TDateTimeField;
    CadE075DerHORPAL: TIntegerField;
    CadE075DerEXPWMS: TIntegerField;
    CadE075DerSERMVP: TStringField;
    CadE075DerAPRDFT: TStringField;
    CadE075DerCODAEM: TStringField;
    CadE075DerCODPDV: TIntegerField;
    CadE075DerINDGEN: TStringField;
    CadE075DerQTDMLT: TFMTBCDField;
    CadE075DerQTDMIN: TFMTBCDField;
    CadE075DerQTDMAX: TFMTBCDField;
    CadE075DerCODEND: TStringField;
    CadE075DerROTANX: TIntegerField;
    CadE075DerNUMANX: TBCDField;
    CadE075DerINDPCQ: TStringField;
    CadE075DerVLRCID: TBCDField;
    CadE075DerQTDCUS: TFMTBCDField;
    CadE075DerUSU_CORUNI: TBCDField;
    CadE075DerUSU_CMP1BB: TBCDField;
    CadE075DerUSU_CMP1AE: TBCDField;
    CadE075DerUSU_CMP2BB: TBCDField;
    CadE075DerUSU_CMP2EN: TBCDField;
    CadE075DerUSU_MEDESP: TStringField;
    CadE075DerUSU_FATOR: TBCDField;
    ConsGeral: TADOQuery;
    CadUsu_TSalCusUSU_CUSATU: TBCDField;
    CadUsu_TCanSal: TADOQuery;
    CadUsu_TCanSalUSU_CODEMP: TIntegerField;
    CadUsu_TCanSalUSU_CODFIL: TIntegerField;
    CadUsu_TCanSalUSU_NUMOCP: TIntegerField;
    CadUsu_TCanSalUSU_SEQIPO: TIntegerField;
    CadUsu_TCanSalUSU_DATCAN: TDateTimeField;
    CadUsu_TCanSalUSU_SALCAN: TStringField;
    CadUsu_TCanSalUSU_USUCAN: TBCDField;
    CadUsu_TCanSalUSU_CODPRO: TStringField;
    CadUsu_TCanSalUSU_QTDPED: TBCDField;
    CadUsu_TCanSalUSU_QTDREC: TBCDField;
    CadUsu_TCanSalUSU_QTDCAN: TBCDField;
    ConsDistintaProdutos: TADOQuery;
    ConsDistintaProdutosCODPRO: TStringField;
    ConsDistintaProdutosCODDER: TStringField;
    ConsDistintaProdutosQTDABE: TFMTBCDField;
    ConsDistintaProdutosQTDPED: TFMTBCDField;
    ConsDistintaProdutosQTDCAN: TFMTBCDField;
    ConsDistintaProdutosQTDFAT: TFMTBCDField;
    ConsDistintaProdutosDESPRO: TStringField;
    ConsDistintaProdutosDESDER: TStringField;
    ConsDistintaProdutosVOLDER: TFMTBCDField;
    ConsDistintaProdutosvnVolDer: TFloatField;
    CadUsu_TempTcp: TADOQuery;
    CadUsu_TempTcpUSU_CODPRO: TStringField;
    CadUsu_TempTcpUSU_QTDCON: TBCDField;
    CadUsu_TempTcpUSU_SAL1001: TBCDField;
    CadUsu_TempTcpUSU_SAL1001_1: TBCDField;
    CadUsu_TempTcpUSU_SALFIM: TBCDField;
    ConsUsu_TempTcp: TADOQuery;
    ConsUsu_TempTcpUSU_CODPRO: TStringField;
    ConsUsu_TempTcpUSU_QTDCON: TBCDField;
    ConsUsu_TempTcpUSU_SAL1001: TBCDField;
    ConsUsu_TempTcpUSU_SAL1001_1: TBCDField;
    ConsUsu_TempTcpUSU_SALFIM: TBCDField;
    CadE075DerQTDEMB: TFMTBCDField;
    ConsE120PedAdd: TADOQuery;
    ConsE120PedAddCODEMP: TIntegerField;
    ConsE120PedAddCODFIL: TIntegerField;
    ConsE120PedAddNUMPED: TIntegerField;
    ConsE120PedAddTIPPED: TIntegerField;
    ConsE120PedAddPRCPED: TIntegerField;
    ConsE120PedAddTNSPRO: TStringField;
    ConsE120PedAddTNSSER: TStringField;
    ConsE120PedAddDATEMI: TDateTimeField;
    ConsE120PedAddHOREMI: TIntegerField;
    ConsE120PedAddDATPRV: TDateTimeField;
    ConsE120PedAddHORPRV: TIntegerField;
    ConsE120PedAddOBSPED: TStringField;
    ConsE120PedAddCODCLI: TIntegerField;
    ConsE120PedAddCATCLI: TIntegerField;
    ConsE120PedAddQTDVPF: TIntegerField;
    ConsE120PedAddQTDMFP: TIntegerField;
    ConsE120PedAddINDAGR: TStringField;
    ConsE120PedAddSEQENT: TIntegerField;
    ConsE120PedAddSEQCOB: TIntegerField;
    ConsE120PedAddSEQCTO: TIntegerField;
    ConsE120PedAddPEDCLI: TStringField;
    ConsE120PedAddCODROE: TStringField;
    ConsE120PedAddSEQROE: TIntegerField;
    ConsE120PedAddCODREP: TIntegerField;
    ConsE120PedAddCODMOE: TStringField;
    ConsE120PedAddCODMCP: TStringField;
    ConsE120PedAddDATMFP: TDateTimeField;
    ConsE120PedAddCOTMFP: TFMTBCDField;
    ConsE120PedAddDATMOE: TDateTimeField;
    ConsE120PedAddCOTMOE: TFMTBCDField;
    ConsE120PedAddFECMOE: TStringField;
    ConsE120PedAddCODFCR: TStringField;
    ConsE120PedAddDATFCR: TDateTimeField;
    ConsE120PedAddCODCPG: TStringField;
    ConsE120PedAddPGTANT: TStringField;
    ConsE120PedAddCODFPG: TIntegerField;
    ConsE120PedAddQTDABE: TFMTBCDField;
    ConsE120PedAddQTDAEN: TFMTBCDField;
    ConsE120PedAddCODTRA: TIntegerField;
    ConsE120PedAddCODRED: TIntegerField;
    ConsE120PedAddCODVIA: TStringField;
    ConsE120PedAddPLAVEI: TStringField;
    ConsE120PedAddVLRFUM: TBCDField;
    ConsE120PedAddQTDFRE: TFMTBCDField;
    ConsE120PedAddFORFRE: TIntegerField;
    ConsE120PedAddVLRFRE: TBCDField;
    ConsE120PedAddCIFFOB: TStringField;
    ConsE120PedAddVLRSEG: TBCDField;
    ConsE120PedAddVLREMB: TBCDField;
    ConsE120PedAddVLRENC: TBCDField;
    ConsE120PedAddVLROUT: TBCDField;
    ConsE120PedAddVLRDAR: TBCDField;
    ConsE120PedAddVLRFRD: TBCDField;
    ConsE120PedAddVLROUD: TBCDField;
    ConsE120PedAddPERDS1: TBCDField;
    ConsE120PedAddPERDS2: TBCDField;
    ConsE120PedAddPERDS3: TBCDField;
    ConsE120PedAddPERDS4: TBCDField;
    ConsE120PedAddVLRBPR: TBCDField;
    ConsE120PedAddVLRDPR: TBCDField;
    ConsE120PedAddVLRBSE: TBCDField;
    ConsE120PedAddVLRDSE: TBCDField;
    ConsE120PedAddVLRDS1: TBCDField;
    ConsE120PedAddVLRDS2: TBCDField;
    ConsE120PedAddVLRDS3: TBCDField;
    ConsE120PedAddVLRDS4: TBCDField;
    ConsE120PedAddVLROFE: TBCDField;
    ConsE120PedAddVLRDZF: TBCDField;
    ConsE120PedAddVLRBIP: TBCDField;
    ConsE120PedAddVLRIPI: TBCDField;
    ConsE120PedAddVLRBIC: TBCDField;
    ConsE120PedAddVLRICM: TBCDField;
    ConsE120PedAddVLRBSI: TBCDField;
    ConsE120PedAddVLRSIC: TBCDField;
    ConsE120PedAddVLRBSP: TBCDField;
    ConsE120PedAddVLRSTP: TBCDField;
    ConsE120PedAddVLRBSC: TBCDField;
    ConsE120PedAddVLRSTC: TBCDField;
    ConsE120PedAddVLRBIS: TBCDField;
    ConsE120PedAddVLRISS: TBCDField;
    ConsE120PedAddVLRBIR: TBCDField;
    ConsE120PedAddVLRIRF: TBCDField;
    ConsE120PedAddVLRBIN: TBCDField;
    ConsE120PedAddVLRINS: TBCDField;
    ConsE120PedAddVLRBCO: TBCDField;
    ConsE120PedAddVLRCOM: TBCDField;
    ConsE120PedAddVLRLPR: TBCDField;
    ConsE120PedAddVLRLSE: TBCDField;
    ConsE120PedAddVLRLOU: TBCDField;
    ConsE120PedAddVLRLIQ: TBCDField;
    ConsE120PedAddVLRFIN: TBCDField;
    ConsE120PedAddVLRADT: TBCDField;
    ConsE120PedAddQTDORI: TFMTBCDField;
    ConsE120PedAddVLRORI: TBCDField;
    ConsE120PedAddTEMPAR: TStringField;
    ConsE120PedAddCODPOR: TStringField;
    ConsE120PedAddCODCRT: TStringField;
    ConsE120PedAddSITPED: TIntegerField;
    ConsE120PedAddCODMOT: TIntegerField;
    ConsE120PedAddOBSMOT: TStringField;
    ConsE120PedAddPEDBLO: TStringField;
    ConsE120PedAddUSUBLO: TBCDField;
    ConsE120PedAddDATBLO: TDateTimeField;
    ConsE120PedAddHORBLO: TIntegerField;
    ConsE120PedAddINDSIG: TStringField;
    ConsE120PedAddVERCAL: TIntegerField;
    ConsE120PedAddHORINI: TIntegerField;
    ConsE120PedAddHORFIM: TIntegerField;
    ConsE120PedAddUSUGER: TBCDField;
    ConsE120PedAddDATGER: TDateTimeField;
    ConsE120PedAddHORGER: TIntegerField;
    ConsE120PedAddPERFRE: TBCDField;
    ConsE120PedAddPERSEG: TBCDField;
    ConsE120PedAddPEREMB: TBCDField;
    ConsE120PedAddPERENC: TBCDField;
    ConsE120PedAddPEROUT: TBCDField;
    ConsE120PedAddCODSAC: TBCDField;
    ConsE120PedAddCODOPE: TIntegerField;
    ConsE120PedAddCODVEN: TIntegerField;
    ConsE120PedAddPEDPAL: TIntegerField;
    ConsE120PedAddACEPAR: TStringField;
    ConsE120PedAddPEROF1: TBCDField;
    ConsE120PedAddPEROF2: TBCDField;
    ConsE120PedAddUSUFEC: TBCDField;
    ConsE120PedAddDATFEC: TDateTimeField;
    ConsE120PedAddHORFEC: TIntegerField;
    ConsE120PedAddCLIREL: TIntegerField;
    ConsE120PedAddVLRBCL: TBCDField;
    ConsE120PedAddVLRCSL: TBCDField;
    ConsE120PedAddVLRBPT: TBCDField;
    ConsE120PedAddVLRPIT: TBCDField;
    ConsE120PedAddVLRBCT: TBCDField;
    ConsE120PedAddVLRCRT: TBCDField;
    ConsE120PedAddVLRBOR: TBCDField;
    ConsE120PedAddVLROUR: TBCDField;
    ConsE120PedAddCODMAR: TStringField;
    ConsE120PedAddCODSRO: TStringField;
    ConsE120PedAddFILFAT: TIntegerField;
    ConsE120PedAddCODCDI: TIntegerField;
    ConsE120PedAddCODLIP: TStringField;
    ConsE120PedAddCEPFRE: TIntegerField;
    ConsE120PedAddVLRRIS: TBCDField;
    ConsE120PedAddANAEMB: TStringField;
    ConsE120PedAddNUMEMP: TStringField;
    ConsE120PedAddQTDANE: TIntegerField;
    ConsE120PedAddDATAGE: TDateTimeField;
    ConsE120PedAddFILNCO: TIntegerField;
    ConsE120PedAddSNFNCO: TStringField;
    ConsE120PedAddNUMNCO: TIntegerField;
    ConsE120PedAddEXPWMS: TIntegerField;
    ConsE120PedAddVLRBPF: TBCDField;
    ConsE120PedAddVLRPIF: TBCDField;
    ConsE120PedAddVLRBCF: TBCDField;
    ConsE120PedAddVLRCFF: TBCDField;
    ConsE120PedAddCODAPC: TIntegerField;
    ConsE120PedAddSOMFRE: TStringField;
    ConsE120PedAddQTDITP: TIntegerField;
    ConsE120PedAddQTDITS: TIntegerField;
    ConsE120PedAddPERDS5: TBCDField;
    ConsE120PedAddVLRDS5: TBCDField;
    ConsE120PedAddROTANX: TIntegerField;
    ConsE120PedAddNUMANX: TBCDField;
    ConsE120PedAddNUMNSU: TBCDField;
    ConsE120PedAddDATNSU: TDateTimeField;
    ConsE120PedAddHORNSU: TIntegerField;
    ConsE120PedAddINDEXP: TIntegerField;
    ConsE120PedAddFATPED: TIntegerField;
    ConsE120PedAddUSU_FILDIV: TIntegerField;
    ConsE120PedAddUSU_PEDDIV: TIntegerField;
    ConsE120PedAddUSU_USUDIV: TBCDField;
    ConsE120PedAddUSU_DATDIV: TDateTimeField;
    ConsE120PedAddUSU_HORDIV: TIntegerField;
    ConsE120PedAddUSU_PEDTRA: TStringField;
    ConsE120PedAddUSU_PRECAR: TIntegerField;
    ConsE120PedAddUSU_USUDES: TBCDField;
    ConsE120PedAddUSU_DATDES: TDateTimeField;
    ConsE120PedAddUSU_HORDES: TIntegerField;
    ConsE120IpdAdd: TADOQuery;
    ConsE120IpdAddCODEMP: TIntegerField;
    ConsE120IpdAddCODFIL: TIntegerField;
    ConsE120IpdAddNUMPED: TIntegerField;
    ConsE120IpdAddSEQIPD: TIntegerField;
    ConsE120IpdAddTNSPRO: TStringField;
    ConsE120IpdAddPEDCLI: TStringField;
    ConsE120IpdAddSEQPCL: TStringField;
    ConsE120IpdAddPEDPRV: TStringField;
    ConsE120IpdAddCODPRO: TStringField;
    ConsE120IpdAddCODDER: TStringField;
    ConsE120IpdAddCPLIPD: TStringField;
    ConsE120IpdAddCODFAM: TStringField;
    ConsE120IpdAddCODAGR: TIntegerField;
    ConsE120IpdAddCODTIC: TStringField;
    ConsE120IpdAddCODTRD: TStringField;
    ConsE120IpdAddCODTST: TStringField;
    ConsE120IpdAddCODSTP: TStringField;
    ConsE120IpdAddCODSTC: TStringField;
    ConsE120IpdAddCODDEP: TStringField;
    ConsE120IpdAddCODLOT: TStringField;
    ConsE120IpdAddRESEST: TStringField;
    ConsE120IpdAddQTDPED: TFMTBCDField;
    ConsE120IpdAddQTDAEN: TFMTBCDField;
    ConsE120IpdAddQTDPOC: TFMTBCDField;
    ConsE120IpdAddQTDFAT: TFMTBCDField;
    ConsE120IpdAddQTDCAN: TFMTBCDField;
    ConsE120IpdAddQTDABE: TFMTBCDField;
    ConsE120IpdAddQTDRAE: TFMTBCDField;
    ConsE120IpdAddQTDNLP: TFMTBCDField;
    ConsE120IpdAddQTDRES: TFMTBCDField;
    ConsE120IpdAddUNIMED: TStringField;
    ConsE120IpdAddCODMCP: TStringField;
    ConsE120IpdAddDATMFP: TDateTimeField;
    ConsE120IpdAddCOTMFP: TFMTBCDField;
    ConsE120IpdAddDATMOE: TDateTimeField;
    ConsE120IpdAddCOTMOE: TFMTBCDField;
    ConsE120IpdAddFECMOE: TStringField;
    ConsE120IpdAddCODTPR: TStringField;
    ConsE120IpdAddPREUNI: TFMTBCDField;
    ConsE120IpdAddCODMOE: TStringField;
    ConsE120IpdAddPREFIX: TStringField;
    ConsE120IpdAddPERDSC: TBCDField;
    ConsE120IpdAddPEROFE: TBCDField;
    ConsE120IpdAddPERACR: TBCDField;
    ConsE120IpdAddPERIPI: TBCDField;
    ConsE120IpdAddPERICM: TBCDField;
    ConsE120IpdAddPERCOM: TBCDField;
    ConsE120IpdAddDATENT: TDateTimeField;
    ConsE120IpdAddDATANE: TDateTimeField;
    ConsE120IpdAddDATPOC: TDateTimeField;
    ConsE120IpdAddCODPVP: TStringField;
    ConsE120IpdAddNUMPRJ: TIntegerField;
    ConsE120IpdAddCODFPJ: TIntegerField;
    ConsE120IpdAddCTAFIN: TIntegerField;
    ConsE120IpdAddCTARED: TIntegerField;
    ConsE120IpdAddCODCCU: TStringField;
    ConsE120IpdAddVLRFRE: TBCDField;
    ConsE120IpdAddVLRSEG: TBCDField;
    ConsE120IpdAddVLREMB: TBCDField;
    ConsE120IpdAddVLRENC: TBCDField;
    ConsE120IpdAddVLROUT: TBCDField;
    ConsE120IpdAddVLRDAR: TBCDField;
    ConsE120IpdAddVLRFRD: TBCDField;
    ConsE120IpdAddVLROUD: TBCDField;
    ConsE120IpdAddVLRBRU: TBCDField;
    ConsE120IpdAddVLRDSC: TBCDField;
    ConsE120IpdAddVLRDS1: TBCDField;
    ConsE120IpdAddVLRDS2: TBCDField;
    ConsE120IpdAddVLRDS3: TBCDField;
    ConsE120IpdAddVLRDS4: TBCDField;
    ConsE120IpdAddVLROFE: TBCDField;
    ConsE120IpdAddVLRDZF: TBCDField;
    ConsE120IpdAddVLRBIP: TBCDField;
    ConsE120IpdAddVLRIPI: TBCDField;
    ConsE120IpdAddVLRBIC: TBCDField;
    ConsE120IpdAddVLRICM: TBCDField;
    ConsE120IpdAddVLRBSI: TBCDField;
    ConsE120IpdAddVLRICS: TBCDField;
    ConsE120IpdAddVLRBSP: TBCDField;
    ConsE120IpdAddVLRSTP: TBCDField;
    ConsE120IpdAddVLRBSC: TBCDField;
    ConsE120IpdAddVLRSTC: TBCDField;
    ConsE120IpdAddVLRBCO: TBCDField;
    ConsE120IpdAddVLRCOM: TBCDField;
    ConsE120IpdAddVLRLPR: TBCDField;
    ConsE120IpdAddVLRLOU: TBCDField;
    ConsE120IpdAddVLRLIQ: TBCDField;
    ConsE120IpdAddVLRFIN: TBCDField;
    ConsE120IpdAddSITIPD: TIntegerField;
    ConsE120IpdAddCODMOT: TIntegerField;
    ConsE120IpdAddOBSMOT: TStringField;
    ConsE120IpdAddGERNEC: TIntegerField;
    ConsE120IpdAddGERCGA: TStringField;
    ConsE120IpdAddRESMAN: TStringField;
    ConsE120IpdAddINDAED: TStringField;
    ConsE120IpdAddNUMCTR: TIntegerField;
    ConsE120IpdAddDATCPT: TDateTimeField;
    ConsE120IpdAddSEQCVP: TIntegerField;
    ConsE120IpdAddUSUGER: TBCDField;
    ConsE120IpdAddDATGER: TDateTimeField;
    ConsE120IpdAddHORGER: TIntegerField;
    ConsE120IpdAddQTDPPF: TFMTBCDField;
    ConsE120IpdAddCMPKIT: TStringField;
    ConsE120IpdAddFILOCP: TIntegerField;
    ConsE120IpdAddNUMOCP: TIntegerField;
    ConsE120IpdAddSEQIPO: TIntegerField;
    ConsE120IpdAddUNIVEN: TStringField;
    ConsE120IpdAddQTDVEN: TFMTBCDField;
    ConsE120IpdAddPREVEN: TFMTBCDField;
    ConsE120IpdAddPREBRU: TFMTBCDField;
    ConsE120IpdAddFILCTR: TIntegerField;
    ConsE120IpdAddCTRCVS: TIntegerField;
    ConsE120IpdAddCPTCVS: TDateTimeField;
    ConsE120IpdAddSEQCVS: TIntegerField;
    ConsE120IpdAddCODAVC: TIntegerField;
    ConsE120IpdAddCODFXA: TStringField;
    ConsE120IpdAddCODPGR: TStringField;
    ConsE120IpdAddIDXGRD: TIntegerField;
    ConsE120IpdAddCODMAR: TStringField;
    ConsE120IpdAddCODCLC: TStringField;
    ConsE120IpdAddPERDS1: TBCDField;
    ConsE120IpdAddPERDS2: TBCDField;
    ConsE120IpdAddPERDS3: TBCDField;
    ConsE120IpdAddPERDS4: TBCDField;
    ConsE120IpdAddFILPRD: TIntegerField;
    ConsE120IpdAddVLRRIS: TBCDField;
    ConsE120IpdAddINDPCE: TStringField;
    ConsE120IpdAddINDPCR: TStringField;
    ConsE120IpdAddPERPIT: TBCDField;
    ConsE120IpdAddVLRBPT: TBCDField;
    ConsE120IpdAddVLRPIT: TBCDField;
    ConsE120IpdAddPERCRT: TBCDField;
    ConsE120IpdAddVLRBCT: TBCDField;
    ConsE120IpdAddVLRCRT: TBCDField;
    ConsE120IpdAddPERCSL: TBCDField;
    ConsE120IpdAddVLRBCL: TBCDField;
    ConsE120IpdAddVLRCSL: TBCDField;
    ConsE120IpdAddPEROUR: TBCDField;
    ConsE120IpdAddVLRBOR: TBCDField;
    ConsE120IpdAddVLROUR: TBCDField;
    ConsE120IpdAddPERIRF: TBCDField;
    ConsE120IpdAddVLRBIR: TBCDField;
    ConsE120IpdAddVLRIRF: TBCDField;
    ConsE120IpdAddFILNFC: TIntegerField;
    ConsE120IpdAddFORNFC: TIntegerField;
    ConsE120IpdAddNUMNFC: TIntegerField;
    ConsE120IpdAddSNFNFC: TStringField;
    ConsE120IpdAddSEQIPC: TIntegerField;
    ConsE120IpdAddNCTLCL: TStringField;
    ConsE120IpdAddNRECLI: TStringField;
    ConsE120IpdAddNOSICL: TBCDField;
    ConsE120IpdAddNOSFCL: TBCDField;
    ConsE120IpdAddNOCCL1: TStringField;
    ConsE120IpdAddNOCCL2: TStringField;
    ConsE120IpdAddNOCCL3: TStringField;
    ConsE120IpdAddCODAGC: TStringField;
    ConsE120IpdAddCTRCVP: TIntegerField;
    ConsE120IpdAddCPTCVP: TDateTimeField;
    ConsE120IpdAddSEQCTR: TIntegerField;
    ConsE120IpdAddINDAPE: TIntegerField;
    ConsE120IpdAddOBSIPD: TStringField;
    ConsE120IpdAddSEQISP: TIntegerField;
    ConsE120IpdAddEMPOCP: TIntegerField;
    ConsE120IpdAddVLRBPF: TBCDField;
    ConsE120IpdAddPERPIF: TBCDField;
    ConsE120IpdAddVLRPIF: TBCDField;
    ConsE120IpdAddVLRBCF: TBCDField;
    ConsE120IpdAddPERCFF: TBCDField;
    ConsE120IpdAddVLRCFF: TBCDField;
    ConsE120IpdAddPERDS5: TBCDField;
    ConsE120IpdAddVLRDS5: TBCDField;
    ConsE120IpdAddAGRNEC: TStringField;
    ConsE120IpdAddAGRPAI: TStringField;
    ConsE120IpdAddORIRES: TStringField;
    ConsE120IpdAddUSU_TIPCMB: TIntegerField;
    ConsE120IpdAddUSU_CODTEC1: TStringField;
    ConsE120IpdAddUSU_CODTEC2: TStringField;
    ConsE120IpdAddUSU_QTDREP: TIntegerField;
    ConsE120IpdAddUSU_QTDDIV: TBCDField;
    ConsE120IpdAddUSU_MEDLAR: TBCDField;
    ConsE120IpdAddUSU_MEDCOM: TBCDField;
    ConsE120IpdAddUSU_MEDALT: TBCDField;
    ConsE120IpdAddUSU_PERDESC1: TBCDField;
    ConsE120IpdAddUSU_PERDESC2: TBCDField;
    ConsE120IpdAddUSU_PERDESC3: TBCDField;
    ConsE120IpdAddUSU_PERDESC4: TBCDField;
    ConsE120IpdAddUSU_PERDESC5: TBCDField;
    ConsE120IpdAddUSU_PERDESC6: TBCDField;
    ConsE120IpdAddUSU_CANAPR: TFMTBCDField;
    ConsE120IpdAddUSU_TOTDSC: TBCDField;
    ConsE120IpdAddUSU_TOTDSCORI: TBCDField;
    ConsE120IpdAddUSU_VLRORI: TBCDField;
    ConsE120IpdAddDESPRO: TStringField;
    ConsE120IpdAddDESDER: TStringField;
    ConsUsu_T120IpdAdd: TADOQuery;
    ConsUsu_T120IpdAddUSU_CODEMP: TIntegerField;
    ConsUsu_T120IpdAddUSU_CODFIL: TIntegerField;
    ConsUsu_T120IpdAddUSU_NUMPED: TIntegerField;
    ConsUsu_T120IpdAddUSU_SEQIPD: TIntegerField;
    ConsUsu_T120IpdAddUSU_QTDCOR: TIntegerField;
    ConsUsu_T120IpdAddUSU_TIPCMB: TIntegerField;
    ConsUsu_T120IpdAddUSU_COR001: TStringField;
    ConsUsu_T120IpdAddUSU_COR002: TStringField;
    ConsUsu_T120IpdAddUSU_SEQITE: TIntegerField;
    ConsUsu_T120IpdAddUSU_CODPRO: TStringField;
    ConsUsu_T120IpdAddUSU_CODDER: TStringField;
    ConsUsu_T120IpdAddUSU_TECTRA: TStringField;
    ConsUsu_T120IpdAddUSU_QTDABE: TIntegerField;
    ConsUsu_T120IpdAddUSU_QTDCAN: TIntegerField;
    ConsUsu_T120IpdAddUSU_NUMANE: TBCDField;
    ConsUsu_T120IpdAddUSU_PRECAR: TIntegerField;
    CadUsu_T120IpdUSU_NUMCOM: TIntegerField;
    ConsE120PedA: TADOQuery;
    ConsE120PedACODEMP: TIntegerField;
    ConsE120PedACODFIL: TIntegerField;
    ConsE120PedANUMPED: TIntegerField;
    ConsE120PedATIPPED: TIntegerField;
    ConsE120PedAPRCPED: TIntegerField;
    ConsE120PedATNSPRO: TStringField;
    ConsE120PedATNSSER: TStringField;
    ConsE120PedADATEMI: TDateTimeField;
    ConsE120PedAHOREMI: TIntegerField;
    ConsE120PedADATPRV: TDateTimeField;
    ConsE120PedAHORPRV: TIntegerField;
    ConsE120PedAOBSPED: TStringField;
    ConsE120PedACODCLI: TIntegerField;
    ConsE120PedACATCLI: TIntegerField;
    ConsE120PedAQTDVPF: TIntegerField;
    ConsE120PedAQTDMFP: TIntegerField;
    ConsE120PedAINDAGR: TStringField;
    ConsE120PedASEQENT: TIntegerField;
    ConsE120PedASEQCOB: TIntegerField;
    ConsE120PedASEQCTO: TIntegerField;
    ConsE120PedAPEDCLI: TStringField;
    ConsE120PedACODROE: TStringField;
    ConsE120PedASEQROE: TIntegerField;
    ConsE120PedACODREP: TIntegerField;
    ConsE120PedACODMOE: TStringField;
    ConsE120PedACODMCP: TStringField;
    ConsE120PedADATMFP: TDateTimeField;
    ConsE120PedACOTMFP: TFMTBCDField;
    ConsE120PedADATMOE: TDateTimeField;
    ConsE120PedACOTMOE: TFMTBCDField;
    ConsE120PedAFECMOE: TStringField;
    ConsE120PedACODFCR: TStringField;
    ConsE120PedADATFCR: TDateTimeField;
    ConsE120PedACODCPG: TStringField;
    ConsE120PedAPGTANT: TStringField;
    ConsE120PedACODFPG: TIntegerField;
    ConsE120PedAQTDABE: TFMTBCDField;
    ConsE120PedAQTDAEN: TFMTBCDField;
    ConsE120PedACODTRA: TIntegerField;
    ConsE120PedACODRED: TIntegerField;
    ConsE120PedACODVIA: TStringField;
    ConsE120PedAPLAVEI: TStringField;
    ConsE120PedAVLRFUM: TBCDField;
    ConsE120PedAQTDFRE: TFMTBCDField;
    ConsE120PedAFORFRE: TIntegerField;
    ConsE120PedAVLRFRE: TBCDField;
    ConsE120PedACIFFOB: TStringField;
    ConsE120PedAVLRSEG: TBCDField;
    ConsE120PedAVLREMB: TBCDField;
    ConsE120PedAVLRENC: TBCDField;
    ConsE120PedAVLROUT: TBCDField;
    ConsE120PedAVLRDAR: TBCDField;
    ConsE120PedAVLRFRD: TBCDField;
    ConsE120PedAVLROUD: TBCDField;
    ConsE120PedAPERDS1: TBCDField;
    ConsE120PedAPERDS2: TBCDField;
    ConsE120PedAPERDS3: TBCDField;
    ConsE120PedAPERDS4: TBCDField;
    ConsE120PedAVLRBPR: TBCDField;
    ConsE120PedAVLRDPR: TBCDField;
    ConsE120PedAVLRBSE: TBCDField;
    ConsE120PedAVLRDSE: TBCDField;
    ConsE120PedAVLRDS1: TBCDField;
    ConsE120PedAVLRDS2: TBCDField;
    ConsE120PedAVLRDS3: TBCDField;
    ConsE120PedAVLRDS4: TBCDField;
    ConsE120PedAVLROFE: TBCDField;
    ConsE120PedAVLRDZF: TBCDField;
    ConsE120PedAVLRBIP: TBCDField;
    ConsE120PedAVLRIPI: TBCDField;
    ConsE120PedAVLRBIC: TBCDField;
    ConsE120PedAVLRICM: TBCDField;
    ConsE120PedAVLRBSI: TBCDField;
    ConsE120PedAVLRSIC: TBCDField;
    ConsE120PedAVLRBSP: TBCDField;
    ConsE120PedAVLRSTP: TBCDField;
    ConsE120PedAVLRBSC: TBCDField;
    ConsE120PedAVLRSTC: TBCDField;
    ConsE120PedAVLRBIS: TBCDField;
    ConsE120PedAVLRISS: TBCDField;
    ConsE120PedAVLRBIR: TBCDField;
    ConsE120PedAVLRIRF: TBCDField;
    ConsE120PedAVLRBIN: TBCDField;
    ConsE120PedAVLRINS: TBCDField;
    ConsE120PedAVLRBCO: TBCDField;
    ConsE120PedAVLRCOM: TBCDField;
    ConsE120PedAVLRLPR: TBCDField;
    ConsE120PedAVLRLSE: TBCDField;
    ConsE120PedAVLRLOU: TBCDField;
    ConsE120PedAVLRLIQ: TBCDField;
    ConsE120PedAVLRFIN: TBCDField;
    ConsE120PedAVLRADT: TBCDField;
    ConsE120PedAQTDORI: TFMTBCDField;
    ConsE120PedAVLRORI: TBCDField;
    ConsE120PedATEMPAR: TStringField;
    ConsE120PedACODPOR: TStringField;
    ConsE120PedACODCRT: TStringField;
    ConsE120PedASITPED: TIntegerField;
    ConsE120PedACODMOT: TIntegerField;
    ConsE120PedAOBSMOT: TStringField;
    ConsE120PedAPEDBLO: TStringField;
    ConsE120PedAUSUBLO: TBCDField;
    ConsE120PedADATBLO: TDateTimeField;
    ConsE120PedAHORBLO: TIntegerField;
    ConsE120PedAINDSIG: TStringField;
    ConsE120PedAVERCAL: TIntegerField;
    ConsE120PedAHORINI: TIntegerField;
    ConsE120PedAHORFIM: TIntegerField;
    ConsE120PedAUSUGER: TBCDField;
    ConsE120PedADATGER: TDateTimeField;
    ConsE120PedAHORGER: TIntegerField;
    ConsE120PedAPERFRE: TBCDField;
    ConsE120PedAPERSEG: TBCDField;
    ConsE120PedAPEREMB: TBCDField;
    ConsE120PedAPERENC: TBCDField;
    ConsE120PedAPEROUT: TBCDField;
    ConsE120PedACODSAC: TBCDField;
    ConsE120PedACODOPE: TIntegerField;
    ConsE120PedACODVEN: TIntegerField;
    ConsE120PedAPEDPAL: TIntegerField;
    ConsE120PedAACEPAR: TStringField;
    ConsE120PedAPEROF1: TBCDField;
    ConsE120PedAPEROF2: TBCDField;
    ConsE120PedAUSUFEC: TBCDField;
    ConsE120PedADATFEC: TDateTimeField;
    ConsE120PedAHORFEC: TIntegerField;
    ConsE120PedACLIREL: TIntegerField;
    ConsE120PedAVLRBCL: TBCDField;
    ConsE120PedAVLRCSL: TBCDField;
    ConsE120PedAVLRBPT: TBCDField;
    ConsE120PedAVLRPIT: TBCDField;
    ConsE120PedAVLRBCT: TBCDField;
    ConsE120PedAVLRCRT: TBCDField;
    ConsE120PedAVLRBOR: TBCDField;
    ConsE120PedAVLROUR: TBCDField;
    ConsE120PedACODMAR: TStringField;
    ConsE120PedACODSRO: TStringField;
    ConsE120PedAFILFAT: TIntegerField;
    ConsE120PedACODCDI: TIntegerField;
    ConsE120PedACODLIP: TStringField;
    ConsE120PedACEPFRE: TIntegerField;
    ConsE120PedAVLRRIS: TBCDField;
    ConsE120PedAANAEMB: TStringField;
    ConsE120PedANUMEMP: TStringField;
    ConsE120PedAQTDANE: TIntegerField;
    ConsE120PedADATAGE: TDateTimeField;
    ConsE120PedAFILNCO: TIntegerField;
    ConsE120PedASNFNCO: TStringField;
    ConsE120PedANUMNCO: TIntegerField;
    ConsE120PedAEXPWMS: TIntegerField;
    ConsE120PedAVLRBPF: TBCDField;
    ConsE120PedAVLRPIF: TBCDField;
    ConsE120PedAVLRBCF: TBCDField;
    ConsE120PedAVLRCFF: TBCDField;
    ConsE120PedACODAPC: TIntegerField;
    ConsE120PedASOMFRE: TStringField;
    ConsE120PedAQTDITP: TIntegerField;
    ConsE120PedAQTDITS: TIntegerField;
    ConsE120PedAPERDS5: TBCDField;
    ConsE120PedAVLRDS5: TBCDField;
    ConsE120PedAROTANX: TIntegerField;
    ConsE120PedANUMANX: TBCDField;
    ConsE120PedANUMNSU: TBCDField;
    ConsE120PedADATNSU: TDateTimeField;
    ConsE120PedAHORNSU: TIntegerField;
    ConsE120PedAINDEXP: TIntegerField;
    ConsE120PedAFATPED: TIntegerField;
    ConsE120PedAQTDBPF: TBCDField;
    ConsE120PedAQTDBCF: TBCDField;
    ConsE120PedAQTDBIP: TBCDField;
    ConsE120PedAUSU_FILDIV: TIntegerField;
    ConsE120PedAUSU_PEDDIV: TIntegerField;
    ConsE120PedAUSU_USUDIV: TBCDField;
    ConsE120PedAUSU_DATDIV: TDateTimeField;
    ConsE120PedAUSU_HORDIV: TIntegerField;
    ConsE120PedAUSU_PEDTRA: TStringField;
    ConsE120PedAUSU_PRECAR: TIntegerField;
    ConsE120PedAUSU_USUDES: TBCDField;
    ConsE120PedAUSU_DATDES: TDateTimeField;
    ConsE120PedAUSU_HORDES: TIntegerField;
    ConsE120PedAUSU_NUMCOM: TIntegerField;
    ConsE120IpdA: TADOQuery;
    ConsE120IpdACODEMP: TIntegerField;
    ConsE120IpdACODFIL: TIntegerField;
    ConsE120IpdANUMPED: TIntegerField;
    ConsE120IpdASEQIPD: TIntegerField;
    ConsE120IpdATNSPRO: TStringField;
    ConsE120IpdAPEDCLI: TStringField;
    ConsE120IpdASEQPCL: TStringField;
    ConsE120IpdAPEDPRV: TStringField;
    ConsE120IpdACODPRO: TStringField;
    ConsE120IpdACODDER: TStringField;
    ConsE120IpdACPLIPD: TStringField;
    ConsE120IpdACODFAM: TStringField;
    ConsE120IpdACODAGR: TIntegerField;
    ConsE120IpdACODTIC: TStringField;
    ConsE120IpdACODTRD: TStringField;
    ConsE120IpdACODTST: TStringField;
    ConsE120IpdACODSTP: TStringField;
    ConsE120IpdACODSTC: TStringField;
    ConsE120IpdACODDEP: TStringField;
    ConsE120IpdACODLOT: TStringField;
    ConsE120IpdARESEST: TStringField;
    ConsE120IpdAQTDPED: TFMTBCDField;
    ConsE120IpdAQTDAEN: TFMTBCDField;
    ConsE120IpdAQTDPOC: TFMTBCDField;
    ConsE120IpdAQTDFAT: TFMTBCDField;
    ConsE120IpdAQTDCAN: TFMTBCDField;
    ConsE120IpdAQTDABE: TFMTBCDField;
    ConsE120IpdAQTDRAE: TFMTBCDField;
    ConsE120IpdAQTDNLP: TFMTBCDField;
    ConsE120IpdAQTDRES: TFMTBCDField;
    ConsE120IpdAUNIMED: TStringField;
    ConsE120IpdACODMCP: TStringField;
    ConsE120IpdADATMFP: TDateTimeField;
    ConsE120IpdACOTMFP: TFMTBCDField;
    ConsE120IpdADATMOE: TDateTimeField;
    ConsE120IpdACOTMOE: TFMTBCDField;
    ConsE120IpdAFECMOE: TStringField;
    ConsE120IpdACODTPR: TStringField;
    ConsE120IpdAPREUNI: TFMTBCDField;
    ConsE120IpdACODMOE: TStringField;
    ConsE120IpdAPREFIX: TStringField;
    ConsE120IpdAPERDSC: TBCDField;
    ConsE120IpdAPEROFE: TBCDField;
    ConsE120IpdAPERACR: TBCDField;
    ConsE120IpdAPERIPI: TBCDField;
    ConsE120IpdAPERICM: TBCDField;
    ConsE120IpdAPERCOM: TBCDField;
    ConsE120IpdADATENT: TDateTimeField;
    ConsE120IpdADATANE: TDateTimeField;
    ConsE120IpdADATPOC: TDateTimeField;
    ConsE120IpdACODPVP: TStringField;
    ConsE120IpdANUMPRJ: TIntegerField;
    ConsE120IpdACODFPJ: TIntegerField;
    ConsE120IpdACTAFIN: TIntegerField;
    ConsE120IpdACTARED: TIntegerField;
    ConsE120IpdACODCCU: TStringField;
    ConsE120IpdAVLRFRE: TBCDField;
    ConsE120IpdAVLRSEG: TBCDField;
    ConsE120IpdAVLREMB: TBCDField;
    ConsE120IpdAVLRENC: TBCDField;
    ConsE120IpdAVLROUT: TBCDField;
    ConsE120IpdAVLRDAR: TBCDField;
    ConsE120IpdAVLRFRD: TBCDField;
    ConsE120IpdAVLROUD: TBCDField;
    ConsE120IpdAVLRBRU: TBCDField;
    ConsE120IpdAVLRDSC: TBCDField;
    ConsE120IpdAVLRDS1: TBCDField;
    ConsE120IpdAVLRDS2: TBCDField;
    ConsE120IpdAVLRDS3: TBCDField;
    ConsE120IpdAVLRDS4: TBCDField;
    ConsE120IpdAVLROFE: TBCDField;
    ConsE120IpdAVLRDZF: TBCDField;
    ConsE120IpdAVLRBIP: TBCDField;
    ConsE120IpdAVLRIPI: TBCDField;
    ConsE120IpdAVLRBIC: TBCDField;
    ConsE120IpdAVLRICM: TBCDField;
    ConsE120IpdAVLRBSI: TBCDField;
    ConsE120IpdAVLRICS: TBCDField;
    ConsE120IpdAVLRBSP: TBCDField;
    ConsE120IpdAVLRSTP: TBCDField;
    ConsE120IpdAVLRBSC: TBCDField;
    ConsE120IpdAVLRSTC: TBCDField;
    ConsE120IpdAVLRBCO: TBCDField;
    ConsE120IpdAVLRCOM: TBCDField;
    ConsE120IpdAVLRLPR: TBCDField;
    ConsE120IpdAVLRLOU: TBCDField;
    ConsE120IpdAVLRLIQ: TBCDField;
    ConsE120IpdAVLRFIN: TBCDField;
    ConsE120IpdASITIPD: TIntegerField;
    ConsE120IpdACODMOT: TIntegerField;
    ConsE120IpdAOBSMOT: TStringField;
    ConsE120IpdAGERNEC: TIntegerField;
    ConsE120IpdAGERCGA: TStringField;
    ConsE120IpdARESMAN: TStringField;
    ConsE120IpdAINDAED: TStringField;
    ConsE120IpdANUMCTR: TIntegerField;
    ConsE120IpdADATCPT: TDateTimeField;
    ConsE120IpdASEQCVP: TIntegerField;
    ConsE120IpdAUSUGER: TBCDField;
    ConsE120IpdADATGER: TDateTimeField;
    ConsE120IpdAHORGER: TIntegerField;
    ConsE120IpdAQTDPPF: TFMTBCDField;
    ConsE120IpdACMPKIT: TStringField;
    ConsE120IpdAFILOCP: TIntegerField;
    ConsE120IpdANUMOCP: TIntegerField;
    ConsE120IpdASEQIPO: TIntegerField;
    ConsE120IpdAUNIVEN: TStringField;
    ConsE120IpdAQTDVEN: TFMTBCDField;
    ConsE120IpdAPREVEN: TFMTBCDField;
    ConsE120IpdAPREBRU: TFMTBCDField;
    ConsE120IpdAFILCTR: TIntegerField;
    ConsE120IpdACTRCVS: TIntegerField;
    ConsE120IpdACPTCVS: TDateTimeField;
    ConsE120IpdASEQCVS: TIntegerField;
    ConsE120IpdACODAVC: TIntegerField;
    ConsE120IpdACODFXA: TStringField;
    ConsE120IpdACODPGR: TStringField;
    ConsE120IpdAIDXGRD: TIntegerField;
    ConsE120IpdACODMAR: TStringField;
    ConsE120IpdACODCLC: TStringField;
    ConsE120IpdAPERDS1: TBCDField;
    ConsE120IpdAPERDS2: TBCDField;
    ConsE120IpdAPERDS3: TBCDField;
    ConsE120IpdAPERDS4: TBCDField;
    ConsE120IpdAFILPRD: TIntegerField;
    ConsE120IpdAVLRRIS: TBCDField;
    ConsE120IpdAINDPCE: TStringField;
    ConsE120IpdAINDPCR: TStringField;
    ConsE120IpdAPERPIT: TBCDField;
    ConsE120IpdAVLRBPT: TBCDField;
    ConsE120IpdAVLRPIT: TBCDField;
    ConsE120IpdAPERCRT: TBCDField;
    ConsE120IpdAVLRBCT: TBCDField;
    ConsE120IpdAVLRCRT: TBCDField;
    ConsE120IpdAPERCSL: TBCDField;
    ConsE120IpdAVLRBCL: TBCDField;
    ConsE120IpdAVLRCSL: TBCDField;
    ConsE120IpdAPEROUR: TBCDField;
    ConsE120IpdAVLRBOR: TBCDField;
    ConsE120IpdAVLROUR: TBCDField;
    ConsE120IpdAPERIRF: TBCDField;
    ConsE120IpdAVLRBIR: TBCDField;
    ConsE120IpdAVLRIRF: TBCDField;
    ConsE120IpdAFILNFC: TIntegerField;
    ConsE120IpdAFORNFC: TIntegerField;
    ConsE120IpdANUMNFC: TIntegerField;
    ConsE120IpdASNFNFC: TStringField;
    ConsE120IpdASEQIPC: TIntegerField;
    ConsE120IpdANCTLCL: TStringField;
    ConsE120IpdANRECLI: TStringField;
    ConsE120IpdANOSICL: TBCDField;
    ConsE120IpdANOSFCL: TBCDField;
    ConsE120IpdANOCCL1: TStringField;
    ConsE120IpdANOCCL2: TStringField;
    ConsE120IpdANOCCL3: TStringField;
    ConsE120IpdACODAGC: TStringField;
    ConsE120IpdACTRCVP: TIntegerField;
    ConsE120IpdACPTCVP: TDateTimeField;
    ConsE120IpdASEQCTR: TIntegerField;
    ConsE120IpdAINDAPE: TIntegerField;
    ConsE120IpdAOBSIPD: TStringField;
    ConsE120IpdASEQISP: TIntegerField;
    ConsE120IpdAEMPOCP: TIntegerField;
    ConsE120IpdAVLRBPF: TBCDField;
    ConsE120IpdAPERPIF: TBCDField;
    ConsE120IpdAVLRPIF: TBCDField;
    ConsE120IpdAVLRBCF: TBCDField;
    ConsE120IpdAPERCFF: TBCDField;
    ConsE120IpdAVLRCFF: TBCDField;
    ConsE120IpdAPERDS5: TBCDField;
    ConsE120IpdAVLRDS5: TBCDField;
    ConsE120IpdAAGRNEC: TStringField;
    ConsE120IpdAAGRPAI: TStringField;
    ConsE120IpdAORIRES: TStringField;
    ConsE120IpdAQTDBPF: TBCDField;
    ConsE120IpdAALIPIF: TBCDField;
    ConsE120IpdAQTDBCF: TBCDField;
    ConsE120IpdAALICFF: TBCDField;
    ConsE120IpdAQTDBIP: TBCDField;
    ConsE120IpdAALIIPI: TBCDField;
    ConsE120IpdAUSU_TIPCMB: TIntegerField;
    ConsE120IpdAUSU_CODTEC1: TStringField;
    ConsE120IpdAUSU_CODTEC2: TStringField;
    ConsE120IpdAUSU_QTDREP: TIntegerField;
    ConsE120IpdAUSU_QTDDIV: TBCDField;
    ConsE120IpdAUSU_MEDLAR: TBCDField;
    ConsE120IpdAUSU_MEDCOM: TBCDField;
    ConsE120IpdAUSU_MEDALT: TBCDField;
    ConsE120IpdAUSU_PERDESC1: TBCDField;
    ConsE120IpdAUSU_PERDESC2: TBCDField;
    ConsE120IpdAUSU_PERDESC3: TBCDField;
    ConsE120IpdAUSU_PERDESC4: TBCDField;
    ConsE120IpdAUSU_PERDESC5: TBCDField;
    ConsE120IpdAUSU_PERDESC6: TBCDField;
    ConsE120IpdAUSU_CANAPR: TFMTBCDField;
    ConsE120IpdAUSU_TOTDSC: TBCDField;
    ConsE120IpdAUSU_TOTDSCORI: TBCDField;
    ConsE120IpdAUSU_VLRORI: TBCDField;
    ConsE120IpdAUSU_NUMCOM: TIntegerField;
    ConsE120IpdADESPRO: TStringField;
    ConsE120IpdADESDER: TStringField;
    CadE120IpdA: TADOQuery;
    CadE120IpdAUSU_CODEMP: TIntegerField;
    CadE120IpdAUSU_CODFIL: TIntegerField;
    CadE120IpdAUSU_NUMPED: TIntegerField;
    CadE120IpdAUSU_SEQIPD: TIntegerField;
    CadE120IpdAUSU_VLRPRO: TBCDField;
    CadE120IpdAUSU_INDEV: TStringField;
    CadE120IpdAUSU_DATFAB: TDateTimeField;
    CadE120IpdAUSU_DATSOL: TDateTimeField;
    CadE120IpdAUSU_DATPER: TDateTimeField;
    CadE120IpdAUSU_USUGER: TIntegerField;
    CadE120IpdAUSU_DESPER: TStringField;
    CadE120IpdAUSU_MATUTI: TStringField;
    CadE120IpdAUSU_DESIMG: TStringField;
    CadE120IpdAUSU_ARGSOL: TStringField;
    ConsSaldos: TADOQuery;
    ConsSaldosCODPRO: TStringField;
    ConsSaldosCODDEP: TStringField;
    ConsSaldosQTDEST: TFMTBCDField;
    ConsSaldosUSU_SALRES: TBCDField;
    ConsSaldosUSU_SALFIL: TBCDField;
    CadUsu_TSalTec: TADOQuery;
    CadUsu_TSalTecUSU_CODPRO: TStringField;
    CadUsu_TSalTecUSU_SALRES: TBCDField;
    CadUsu_TSalTecUSU_SALFIL: TBCDField;
    ConsUsu_TCarPro: TADOQuery;
    ConsUsu_TCarProUSU_NUMANE: TIntegerField;
    ConsUsu_TCarProUSU_DATIMP: TDateTimeField;
    ConsUsu_TCarProUSU_HORIMP: TIntegerField;
    ConsUsu_TCarProUSU_USUIMP: TIntegerField;
    ConsUsu_TCarProUSU_CARPRO: TStringField;
    ConsE075Der: TADOQuery;
    ConsE075DerCODEMP: TIntegerField;
    ConsE075DerCODPRO: TStringField;
    ConsE075DerCODDER: TStringField;
    ConsE075DerDESDER: TStringField;
    ConsE075DerDESCPL: TStringField;
    ConsE075DerCODBAR: TBCDField;
    ConsE075DerCODAGR: TIntegerField;
    ConsE075DerCODAGT: TStringField;
    ConsE075DerSEQCMD: TIntegerField;
    ConsE075DerDATVAL: TDateTimeField;
    ConsE075DerDIAVLT: TIntegerField;
    ConsE075DerTIPCN2: TStringField;
    ConsE075DerVLRCN2: TFMTBCDField;
    ConsE075DerTIPCN3: TStringField;
    ConsE075DerVLRCN3: TFMTBCDField;
    ConsE075DerPRECUS: TFMTBCDField;
    ConsE075DerDATCUS: TDateTimeField;
    ConsE075DerPREMED: TFMTBCDField;
    ConsE075DerDATMED: TDateTimeField;
    ConsE075DerPREUEN: TFMTBCDField;
    ConsE075DerDATUEN: TDateTimeField;
    ConsE075DerPREREP: TFMTBCDField;
    ConsE075DerDATREP: TDateTimeField;
    ConsE075DerDIAREP: TIntegerField;
    ConsE075DerPESBRU: TFMTBCDField;
    ConsE075DerPESLIQ: TFMTBCDField;
    ConsE075DerTOLPES: TBCDField;
    ConsE075DerVOLDER: TFMTBCDField;
    ConsE075DerPERPRD: TBCDField;
    ConsE075DerQTDIQL: TFMTBCDField;
    ConsE075DerQTDCIC: TFMTBCDField;
    ConsE075DerQTDPRD: TFMTBCDField;
    ConsE075DerPREUIS: TFMTBCDField;
    ConsE075DerPERICS: TBCDField;
    ConsE075DerCODEMB: TIntegerField;
    ConsE075DerCODROT: TStringField;
    ConsE075DerCODROY: TIntegerField;
    ConsE075DerBXAORP: TStringField;
    ConsE075DerSERCCL: TStringField;
    ConsE075DerNUMCCL: TStringField;
    ConsE075DerCURABC: TStringField;
    ConsE075DerCURAB2: TStringField;
    ConsE075DerCURAB3: TStringField;
    ConsE075DerCURAB4: TStringField;
    ConsE075DerCODREG: TIntegerField;
    ConsE075DerSITDER: TStringField;
    ConsE075DerCODMOT: TIntegerField;
    ConsE075DerCTRLOT: TStringField;
    ConsE075DerCTRSEP: TStringField;
    ConsE075DerCTRVLD: TStringField;
    ConsE075DerDEPPAD: TStringField;
    ConsE075DerDEPPAA: TStringField;
    ConsE075DerINDPCE: TStringField;
    ConsE075DerINDPCR: TStringField;
    ConsE075DerINDKAN: TStringField;
    ConsE075DerCODREF: TStringField;
    ConsE075DerCODPIN: TStringField;
    ConsE075DerNOTFOR: TBCDField;
    ConsE075DerORICUS: TStringField;
    ConsE075DerINFCUS: TStringField;
    ConsE075DerHORCUS: TIntegerField;
    ConsE075DerUSUGER: TBCDField;
    ConsE075DerHORGER: TIntegerField;
    ConsE075DerDATGER: TDateTimeField;
    ConsE075DerUSUALT: TBCDField;
    ConsE075DerHORALT: TIntegerField;
    ConsE075DerDATALT: TDateTimeField;
    ConsE075DerCODAGE: TStringField;
    ConsE075DerCODBA2: TStringField;
    ConsE075DerINDEXP: TIntegerField;
    ConsE075DerDATPAL: TDateTimeField;
    ConsE075DerHORPAL: TIntegerField;
    ConsE075DerEXPWMS: TIntegerField;
    ConsE075DerSERMVP: TStringField;
    ConsE075DerAPRDFT: TStringField;
    ConsE075DerCODAEM: TStringField;
    ConsE075DerCODPDV: TIntegerField;
    ConsE075DerINDGEN: TStringField;
    ConsE075DerQTDMLT: TFMTBCDField;
    ConsE075DerQTDMIN: TFMTBCDField;
    ConsE075DerQTDMAX: TFMTBCDField;
    ConsE075DerCODEND: TStringField;
    ConsE075DerROTANX: TIntegerField;
    ConsE075DerNUMANX: TBCDField;
    ConsE075DerINDPCQ: TStringField;
    ConsE075DerVLRCID: TBCDField;
    ConsE075DerQTDCUS: TFMTBCDField;
    ConsE075DerUSU_CORUNI: TBCDField;
    ConsE075DerUSU_CMP1BB: TBCDField;
    ConsE075DerUSU_CMP1AE: TBCDField;
    ConsE075DerUSU_CMP2BB: TBCDField;
    ConsE075DerUSU_CMP2EN: TBCDField;
    ConsE075DerUSU_MEDESP: TStringField;
    ConsE075DerUSU_FATOR: TBCDField;
    ConsE075DerQTDEMB: TFMTBCDField;
    ConsUsu_TCarProUSU_ITESEL: TStringField;
    ConsUsu_TCarProUSU_OBSCAR: TStringField;
    ClientAltCargaCorteEstof: TClientDataSet;
    ClientAltCargaCorteEstofNUMANE: TIntegerField;
    ClientAltCargaCorteEstofCODPRO: TStringField;
    ClientAltCargaCorteEstofCODDER: TStringField;
    ClientAltCargaCorteEstofCODCOR1: TStringField;
    ClientAltCargaCorteEstofCODCOR2: TStringField;
    ClientAltCargaCorteEstofQTDMOV: TIntegerField;
    ClientAltCargaCorteEstofTIPMOV: TStringField;
    ClientAltCargaCorteEstofDESPRO: TStringField;
    ClientAltCargaCorteEstofSEQOBS: TIntegerField;
    ClientAltCargaCorteEstofImgTipMov: TStringField;
    ConsEstoqueTecidos: TADOQuery;
    ConsEstoqueTecidosCODEMP: TIntegerField;
    ConsEstoqueTecidosCODPRO: TStringField;
    ConsEstoqueTecidosDESPRO: TStringField;
    ConsEstoqueTecidosUSU_VLRMAX: TBCDField;
    ConsEstoqueTecidosPREMED: TFMTBCDField;
    ConsEstoqueTecidosQTDMOV: TFMTBCDField;
    ConsEstoqueTecidosUSU_SALRES: TBCDField;
    ConsEstoqueTecidosUSU_SALFIL: TBCDField;
    ConsEstoqueTecidosQTDEST: TFMTBCDField;
    ConsEstoqueTecidosSALDO_DISP: TFMTBCDField;
    ConsOCTecido: TADOQuery;
    ConsOCTecidoCODEMP: TIntegerField;
    ConsOCTecidoCODFIL: TIntegerField;
    ConsOCTecidoNUMOCP: TIntegerField;
    ConsOCTecidoCODPRO: TStringField;
    ConsOCTecidoQTDPED: TFMTBCDField;
    ConsOCTecidoQTDREC: TFMTBCDField;
    ConsOCTecidoQTDABE: TFMTBCDField;
    ConsOCTecidoDATEMI: TDateTimeField;
    ConsOCTecidoCODFOR: TIntegerField;
    ConsOCTecidoNOMFOR: TStringField;
    ClientConsOCTecido: TClientDataSet;
    ProviderConsOCTecido: TDataSetProvider;
    ClientConsOCTecidoCODEMP: TIntegerField;
    ClientConsOCTecidoCODFIL: TIntegerField;
    ClientConsOCTecidoNUMOCP: TIntegerField;
    ClientConsOCTecidoCODPRO: TStringField;
    ClientConsOCTecidoQTDPED: TFMTBCDField;
    ClientConsOCTecidoQTDREC: TFMTBCDField;
    ClientConsOCTecidoQTDABE: TFMTBCDField;
    ClientConsOCTecidoDATEMI: TDateTimeField;
    ClientConsOCTecidoCODFOR: TIntegerField;
    ClientConsOCTecidoNOMFOR: TStringField;
    ClientConsOCTecidoTOT_ABERTO: TAggregateField;
    ConsFornecedoresTecido: TADOQuery;
    ConsFornecedoresTecidoCODFOR: TIntegerField;
    ConsFornecedoresTecidoNOMFOR: TStringField;
    ConsPrimeiraNfTecido: TADOQuery;
    ConsPrimeiraNfTecidoCODEMP: TIntegerField;
    ConsPrimeiraNfTecidoCODFIL: TIntegerField;
    ConsPrimeiraNfTecidoCODFOR: TIntegerField;
    ConsPrimeiraNfTecidoNUMNFC: TIntegerField;
    ConsPrimeiraNfTecidoCODSNF: TStringField;
    ConsPrimeiraNfTecidoSEQIPC: TIntegerField;
    ConsPrimeiraNfTecidoTNSPRO: TStringField;
    ConsPrimeiraNfTecidoNUMOCP: TIntegerField;
    ConsPrimeiraNfTecidoCODPRO: TStringField;
    ConsPrimeiraNfTecidoQTDREC: TFMTBCDField;
    ConsPrimeiraNfTecidoUNINFC: TStringField;
    ConsPrimeiraNfTecidoQTDEST: TFMTBCDField;
    ConsPrimeiraNfTecidoUNIMED: TStringField;
    ConsPrimeiraNfTecidoPREUNI: TFMTBCDField;
    ConsPrimeiraNfTecidoPREEST: TFMTBCDField;
    ConsPrimeiraNfTecidoPERIPI: TBCDField;
    ConsPrimeiraNfTecidoPERICM: TBCDField;
    ConsPrimeiraNfTecidoVLRBRU: TBCDField;
    ConsPrimeiraNfTecidoVLRIPI: TBCDField;
    ConsPrimeiraNfTecidoVLRICM: TBCDField;
    ConsPrimeiraNfTecidoVLRLIQ: TBCDField;
    ConsPrimeiraNfTecidoPERIPI_1: TBCDField;
    ConsPrimeiraNfTecidoPERICM_1: TBCDField;
    ConsPrimeiraNfTecidoVLRBRU_1: TBCDField;
    ConsPrimeiraNfTecidoVLRIPI_1: TBCDField;
    ConsPrimeiraNfTecidoVLRICM_1: TBCDField;
    ConsPrimeiraNfTecidoVLRLIQ_1: TBCDField;
    ConsPrimeiraNfTecidoDATEMI: TDateTimeField;
    ConsPrimeiraNfTecidoDATENT: TDateTimeField;
    ConsPrimeiraNfTecidoCODCPG: TStringField;
    ConsPrimeiraNfTecidoDESCPG: TStringField;
    ConsPrimeiraNfTecidoQTDTOT: TFMTBCDField;
    ConsE120pedUSU_NUMPEDORI: TIntegerField;
    ConsE120pedUSU_PRECARORI: TIntegerField;
    procedure ConsE120IpdAfterScroll(DataSet: TDataSet);
    procedure ConsE120IpdAAfterScroll(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstof1BeforeInsert(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstof1BeforePost(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstof1AfterInsert(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstofAfterInsert(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstofBeforeInsert(DataSet: TDataSet);
    procedure ClientAltCargaCorteEstofBeforePost(DataSet: TDataSet);
    procedure ConsEstoqueTecidosAfterScroll(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Dm2: TDm2;

implementation

uses UDm, UAssistencia, UAltProdCargaCorteEstof;

{$R *.dfm}

procedure TDm2.ClientAltCargaCorteEstof1AfterInsert(DataSet: TDataSet);
begin
  if FAltProdCargaCorteEstof.rbAdicionar.Checked then
     begin
       ClientAltCargaCorteEstofTIPMOV.Value := 'A';
     end
  else
  if FAltProdCargaCorteEstof.rbExcluir.Checked then
     begin
       ClientAltCargaCorteEstofTIPMOV.Value := 'E';
     end;
  ClientAltCargaCorteEstofSEQOBS.Value := 0;


  FAltProdCargaCorteEstof.dbg1.SelectedIndex := 1;
end;

procedure TDm2.ClientAltCargaCorteEstof1BeforeInsert(DataSet: TDataSet);
begin
  if FAltProdCargaCorteEstof.edtNumAne.Value = 0 then
     begin
        MessageDlg('Informe a Carga',mtWarning,[mbok],0);
        Abort;
     end;

  if (FAltProdCargaCorteEstof.rbAdicionar.Checked = false) and (FAltProdCargaCorteEstof.rbExcluir.Checked = false) then
      begin
        MessageDlg('Informe o tipo de movimento',mtWarning,[mbok],0);
        Abort;
      end;

end;

procedure TDm2.ClientAltCargaCorteEstof1BeforePost(DataSet: TDataSet);
begin
   if ClientAltCargaCorteEstof.State IN [dsInsert,dsEdit] then
      begin
         if FAltProdCargaCorteEstof.edtNumAne.Value = 0 then
           begin
              MessageDlg('Informe a Carga',mtWarning,[mbok],0);
              Abort;
           end;

         if (FAltProdCargaCorteEstof.rbAdicionar.Checked = false) and (FAltProdCargaCorteEstof.rbExcluir.Checked = false) then
            begin
              MessageDlg('Informe o tipo de movimento',mtWarning,[mbok],0);
              Abort;
            end;

         if Trim(ClientAltCargaCorteEstofCODPRO.Value) = '' then
         begin
           MessageDlg('Informe o produto',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODDER.Value) = '' then
         begin
           MessageDlg('Informe a derivação',mtWarning,[mbok],0);
           Abort;
         end;

         if ClientAltCargaCorteEstofQTDMOV.Value = 0 then
         begin
           MessageDlg('Informe a quantidade do movimento',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODCOR1.Value) = '' then
         begin
           MessageDlg('Informe a cor 01',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODCOR2.Value) = '' then
            begin
              ClientAltCargaCorteEstofCODCOR2.Value := ' ';
            end;


        ClientAltCargaCorteEstofNUMANE.Value := FAltProdCargaCorteEstof.edtNumAne.AsInteger;
      end;
end;

procedure TDm2.ClientAltCargaCorteEstofAfterInsert(DataSet: TDataSet);
begin
  if FAltProdCargaCorteEstof.rbAdicionar.Checked then
     begin
       ClientAltCargaCorteEstofTIPMOV.Value := 'A';
     end
  else
  if FAltProdCargaCorteEstof.rbExcluir.Checked then
     begin
       ClientAltCargaCorteEstofTIPMOV.Value := 'E';
     end;
  ClientAltCargaCorteEstofSEQOBS.Value := 0;


  FAltProdCargaCorteEstof.dbg1.SelectedIndex := 1;
end;

procedure TDm2.ClientAltCargaCorteEstofBeforeInsert(DataSet: TDataSet);
begin
if FAltProdCargaCorteEstof.edtNumAne.Value = 0 then
     begin
        MessageDlg('Informe a Carga',mtWarning,[mbok],0);
        Abort;
     end;

  if (FAltProdCargaCorteEstof.rbAdicionar.Checked = false) and (FAltProdCargaCorteEstof.rbExcluir.Checked = false) then
      begin
        MessageDlg('Informe o tipo de movimento',mtWarning,[mbok],0);
        Abort;
      end;
end;

procedure TDm2.ClientAltCargaCorteEstofBeforePost(DataSet: TDataSet);
begin
if ClientAltCargaCorteEstof.State IN [dsInsert,dsEdit] then
      begin
         if FAltProdCargaCorteEstof.edtNumAne.Value = 0 then
           begin
              MessageDlg('Informe a Carga',mtWarning,[mbok],0);
              Abort;
           end;

         if (FAltProdCargaCorteEstof.rbAdicionar.Checked = false) and (FAltProdCargaCorteEstof.rbExcluir.Checked = false) then
            begin
              MessageDlg('Informe o tipo de movimento',mtWarning,[mbok],0);
              Abort;
            end;

         if Trim(ClientAltCargaCorteEstofCODPRO.Value) = '' then
         begin
           MessageDlg('Informe o produto',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODDER.Value) = '' then
         begin
           MessageDlg('Informe a derivação',mtWarning,[mbok],0);
           Abort;
         end;

         if ClientAltCargaCorteEstofQTDMOV.Value = 0 then
         begin
           MessageDlg('Informe a quantidade do movimento',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODCOR1.Value) = '' then
         begin
           MessageDlg('Informe a cor 01',mtWarning,[mbok],0);
           Abort;
         end;

         if Trim(ClientAltCargaCorteEstofCODCOR2.Value) = '' then
            begin
              ClientAltCargaCorteEstofCODCOR2.Value := ' ';
            end;


        ClientAltCargaCorteEstofNUMANE.Value := FAltProdCargaCorteEstof.edtNumAne.AsInteger;
      end;
end;

procedure TDm2.ConsE120IpdAAfterScroll(DataSet: TDataSet);
begin
  CadE120IpdA.Close;
  CadE120IpdA.Parameters.ParamByName('codemp').Value := ConsE120IpdACODEMP.Value;
  CadE120IpdA.Parameters.ParamByName('codfil').Value := ConsE120IpdACODFIL.Value;
  CadE120IpdA.Parameters.ParamByName('numped').Value := ConsE120IpdANUMPED.Value;
  CadE120IpdA.Parameters.ParamByName('seqipd').Value := ConsE120IpdASEQIPD.Value;
  CadE120IpdA.Open;

  FAssistencia.EdCodPro.Text := ConsE120IpdACODPRO.Value;
  FAssistencia.LDsCodPro.Caption := ConsE120IpdADESPRO.Value;
  FAssistencia.EdCodDer.Text := ConsE120IpdACODDER.Value;
  FAssistencia.EdTnsProI.Text := ConsE120IpdATNSPRO.Value;
  FAssistencia.EdDatFab.Date := CadE120IpdAUSU_DATFAB.Value;
  FAssistencia.EdDatSol.Date := CadE120IpdAUSU_DATSOL.Value;
  FAssistencia.EdDatPer.Date := CadE120IpdAUSU_DATPER.Value;
  FAssistencia.MArgSol.Text := CadE120IpdAUSU_ARGSOL.Value;
  FAssistencia.MDesPer.Text := CadE120IpdAUSU_DESPER.Value;
  FAssistencia.MMatUti.Text := CadE120IpdAUSU_MATUTI.Value;
  FAssistencia.EdVlrPro.Value := ConsE120IpdAPREUNI.AsCurrency;
  FAssistencia.EdVlrAst.Value := CadE120IpdAUSU_VLRPRO.AsCurrency;
  if CadE120IpdAUSU_INDEV.Value = 'DEVIDA' then
     FAssistencia.EdInDev.ItemIndex := 1
  else
  if CadE120IpdAUSU_INDEV.Value = 'INDEVIDA' then
     FAssistencia.EdInDev.ItemIndex := 2
  else
     FAssistencia.EdInDev.ItemIndex := 0;

  //consulta a cor do produto
  ConsGeral.Close;
  ConsGeral.SQL.Clear;
  ConsGeral.SQL.Add('select * from usu_t120ipd where usu_codemp = :codemp and');
  ConsGeral.SQL.Add('usu_codfil = :codfil and');
  ConsGeral.SQL.Add('usu_numped = :numped and');
  ConsGeral.SQL.Add('usu_seqipd = :seqipd');
  ConsGeral.SQL.Add('order by usu_seqite');
  ConsGeral.Parameters.ParamByName('codemp').Value := ConsE120IpdACODEMP.Value;
  ConsGeral.Parameters.ParamByName('codfil').Value := ConsE120IpdACODFIL.Value;
  ConsGeral.Parameters.ParamByName('numped').Value := ConsE120IpdANUMPED.Value;
  ConsGeral.Parameters.ParamByName('seqipd').Value := ConsE120IpdASEQIPD.Value;
  ConsGeral.Open;
  FAssistencia.EdCor01.Text := ConsGeral.FieldByName('usu_cor001').AsString;
  FAssistencia.EdCor02.Text := ConsGeral.FieldByName('usu_cor002').AsString;
end;

procedure TDm2.ConsE120IpdAfterScroll(DataSet: TDataSet);
begin
    {ConsUsu_T120Ipd.Close;

    ConsUsu_T120Ipd.Parameters.ParamByName('codfil').Value := ConsE120IpdCODFIL.Value;
    ConsUsu_T120Ipd.Parameters.ParamByName('numped').Value := ConsE120IpdNUMPED.Value;
    ConsUsu_T120Ipd.Parameters.ParamByName('seqipd').Value := ConsE120IpdSEQIPD.Value;
    ConsUsu_T120Ipd.Open;}
end;

procedure TDm2.ConsEstoqueTecidosAfterScroll(DataSet: TDataSet);
begin
  ClientConsOCTecido.Close;
  ConsOCTecido.Close;
  ConsOCTecido.Parameters.ParamByName('CODPRO').Value := ConsEstoqueTecidosCODPRO.Value;
  ConsOCTecido.Open;
  ClientConsOCTecido.Open;

  ConsFornecedoresTecido.Close;
  ConsFornecedoresTecido.Parameters.ParamByName('CODPRO').Value := ConsEstoqueTecidosCODPRO.Value;
  ConsFornecedoresTecido.Open;

  ConsPrimeiraNfTecido.Close;
  ConsPrimeiraNfTecido.Parameters.ParamByName('CODPRO').Value := ConsEstoqueTecidosCODPRO.Value;
  ConsPrimeiraNfTecido.Open;
end;

end.
