unit UDmRave;

interface

uses
  SysUtils, Classes, DB, ADODB, Provider, DBClient, RpBase, RpSystem, RpDefine,
  RpRave, RpCon, RpConDS, RpRender, RpRenderCanvas, RpRenderPrinter;

type
  TDmRave = class(TDataModule)
    ConsE120Ped: TADOQuery;
    ConsE120PedCODEMP: TIntegerField;
    ConsE120PedCODFIL: TIntegerField;
    ConsE120PedNUMPED: TIntegerField;
    ConsE120PedCODCLI: TIntegerField;
    ConsE120PedCODCPG: TStringField;
    ConsE120PedTNSPRO: TStringField;
    ConsE120PedDATEMI: TDateTimeField;
    ConsE120PedCODREP: TIntegerField;
    ConsE120PedVLRLIQ: TBCDField;
    ConsE120PedDESCPG: TStringField;
    ConsE120PedAPEREP: TStringField;
    ConsE120PedDESTNS: TStringField;
    ConsE120PedNOMCLI: TStringField;
    ConsE120PedAPECLI: TStringField;
    ConsE120PedINSEST: TStringField;
    ConsE120PedENDCLI: TStringField;
    ConsE120PedNENCLI: TStringField;
    ConsE120PedCPLEND: TStringField;
    ConsE120PedCEPCLI: TIntegerField;
    ConsE120PedBAICLI: TStringField;
    ConsE120PedCIDCLI: TStringField;
    ConsE120PedSIGUFS: TStringField;
    ConsE120PedCGCCPF: TBCDField;
    ConsE120PedFONCLI: TStringField;
    ConsE120PedVLRBRU: TFMTBCDField;
    ConsE120PedVOLTOT: TFMTBCDField;
    ConsE120Ipd: TADOQuery;
    ConsE120IpdCODEMP: TIntegerField;
    ConsE120IpdCODFIL: TIntegerField;
    ConsE120IpdNUMPED: TIntegerField;
    ConsE120IpdSEQIPD: TIntegerField;
    ConsE120IpdTNSPRO: TStringField;
    ConsE120IpdCODPRO: TStringField;
    ConsE120IpdCODDER: TStringField;
    ConsE120IpdQTDPED: TFMTBCDField;
    ConsE120IpdPREUNI: TFMTBCDField;
    ConsE120IpdVLRBRU: TBCDField;
    ConsE120IpdDESPRO: TStringField;
    ConsE120IpdDESDER: TStringField;
    ConsE120IpdCPLIPD: TStringField;
    ClientConsE120Ipd: TClientDataSet;
    ProviderConsE120Ipd: TDataSetProvider;
    ClientConsE120IpdCODEMP: TIntegerField;
    ClientConsE120IpdCODFIL: TIntegerField;
    ClientConsE120IpdNUMPED: TIntegerField;
    ClientConsE120IpdSEQIPD: TIntegerField;
    ClientConsE120IpdTNSPRO: TStringField;
    ClientConsE120IpdCODPRO: TStringField;
    ClientConsE120IpdCODDER: TStringField;
    ClientConsE120IpdQTDPED: TFMTBCDField;
    ClientConsE120IpdPREUNI: TFMTBCDField;
    ClientConsE120IpdVLRBRU: TBCDField;
    ClientConsE120IpdDESPRO: TStringField;
    ClientConsE120IpdDESDER: TStringField;
    ClientConsE120IpdCPLIPD: TStringField;
    ConsUsu120Ipd: TADOQuery;
    ConsUsu120IpdUSU_QTDCOR: TIntegerField;
    ConsUsu120IpdUSU_TIPCMB: TIntegerField;
    ConsUsu120IpdUSU_COR001: TStringField;
    ConsUsu120IpdUSU_COR002: TStringField;
    RvProjPedido: TRvProject;
    RvSysPedido: TRvSystem;
    RvE120Ped: TRvDataSetConnection;
    RvE120Ipd: TRvDataSetConnection;
    ConsE120Obs: TADOQuery;
    ConsE120ObsOBSPED: TStringField;
    RvE120Obs: TRvDataSetConnection;
    RvConsFaturamento: TRvProject;
    RvSysConsFaturamento: TRvSystem;
    RvClientResultadoFat: TRvDataSetConnection;
    ConsUsu_TAdvAdt: TADOQuery;
    ConsUsu_TAdvAdtUSU_CODEMP: TIntegerField;
    ConsUsu_TAdvAdtUSU_CODFIL: TIntegerField;
    ConsUsu_TAdvAdtUSU_NUMANE: TBCDField;
    ConsUsu_TAdvAdtUSU_NUMADT: TIntegerField;
    ConsUsu_TAdvAdtUSU_TIPADT: TStringField;
    ConsUsu_TAdvAdtUSU_DESADT: TStringField;
    ConsUsu_TAdvAdtUSU_NUMCCO: TStringField;
    ConsUsu_TAdvAdtUSU_NUMCCD: TStringField;
    ConsUsu_TAdvAdtUSU_VLRADT: TBCDField;
    ConsUsu_TAdvAdtUSU_DATADT: TDateTimeField;
    ConsUsu_TAdvAdtUSU_USUADT: TIntegerField;
    ConsUsu_TAdvAdtUSU_SEQMDT: TIntegerField;
    ConsUsu_TAdvAdtUSU_VLRGST: TBCDField;
    ConsUsu_TAdvAdtUSU_VLRRST: TBCDField;
    ConsUsu_TAdvAdtUSU_DATACT: TDateTimeField;
    ConsUsu_TAdvAdtUSU_USUACT: TIntegerField;
    ConsUsu_TAdvAdtUSU_SEQMCT: TIntegerField;
    ConsUsu_TAdvAdtUSU_SITADT: TStringField;
    ConsUsu_TAdvAdtUSU_ITESEL: TStringField;
    ConsUsu_TAdvDsp: TADOQuery;
    ConsUsu_TAdvDspUSU_CODEMP: TIntegerField;
    ConsUsu_TAdvDspUSU_CODFIL: TIntegerField;
    ConsUsu_TAdvDspUSU_NUMANE: TBCDField;
    ConsUsu_TAdvDspUSU_NUMADT: TIntegerField;
    ConsUsu_TAdvDspUSU_SEQDES: TIntegerField;
    ConsUsu_TAdvDspUSU_CODDES: TIntegerField;
    ConsUsu_TAdvDspUSU_DESDES: TStringField;
    ConsUsu_TAdvDspUSU_VLRDES: TBCDField;
    ConsUsu_TAdvDspUSU_DATDES: TDateTimeField;
    ConsUsu_TAdvDspUSU_USUDES: TIntegerField;
    ConsUsu_TAdvDspUSU_CTAFIN: TIntegerField;
    ConsUsu_TAdvDspUSU_CTARED: TIntegerField;
    ConsUsu_TAdvDspUSU_CODCCU: TStringField;
    RvAcertoViagem: TRvProject;
    RvSysAcertoViagem: TRvSystem;
    RvConsUsu_TAdvDsp: TRvDataSetConnection;
    RvConsUsu_TAdvAdt: TRvDataSetConnection;
    RvSaldo1001_1: TRvProject;
    RvSysSaldo1001_1: TRvSystem;
    RvConsUsu_Temp1001_1: TRvDataSetConnection;
    ConsUsu_TRhFun: TADOQuery;
    ConsUsu_TRhFunUSU_NUMCAD: TIntegerField;
    ConsUsu_TRhFunUSU_NOMFUN: TStringField;
    ConsUsu_TRhFunUSU_APEFUN: TStringField;
    ConsUsu_TRhFunUSU_DATADM: TDateTimeField;
    ConsUsu_TRhFunUSU_NUMCPF: TBCDField;
    ConsUsu_TRhFunUSU_TIPCOL: TStringField;
    ConsUsu_TRhFunUSU_CODDEP: TIntegerField;
    ConsUsu_TRhFunUSU_SITAFA: TIntegerField;
    ConsUsu_TRhFunUSU_DESSIT: TStringField;
    ConsUsu_TRhFunUSU_SITDEP: TStringField;
    ConsUsu_TRhFunUSU_GRAPAR: TIntegerField;
    ConsUsu_TRhFunUSU_DESPAR: TStringField;
    RvConvenio_Descontar: TRvProject;
    SysConvenioDescontar: TRvSystem;
    RvConsUsu_TRhFun: TRvDataSetConnection;
    ConsUsu_TRhSerMov: TADOQuery;
    ConsUsu_TRhSerMovUSU_SEQSER: TIntegerField;
    ConsUsu_TRhSerMovUSU_CODSER: TStringField;
    ConsUsu_TRhSerMovUSU_NUMCAD: TIntegerField;
    ConsUsu_TRhSerMovUSU_CODDEP: TIntegerField;
    ConsUsu_TRhSerMovUSU_QTDSER: TIntegerField;
    ConsUsu_TRhSerMovUSU_PREUNI: TBCDField;
    ConsUsu_TRhSerMovUSU_DATSER: TDateTimeField;
    ConsUsu_TRhSerMovUSU_MESSER: TIntegerField;
    ConsUsu_TRhSerMovUSU_ANOSER: TIntegerField;
    ConsUsu_TRhSerMovUSU_NOMFUN: TStringField;
    ConsUsu_TRhSerMovUSU_OBSSER: TStringField;
    ConsUsu_TRhSerMovUSU_INADT: TStringField;
    ConsUsu_TRhSerMovUSU_VLRCOB: TBCDField;
    RvConsUsu_TRhSerMov: TRvDataSetConnection;
    ConsUsu_TSerMovAnalizar: TADOQuery;
    ConsUsu_TSerMovAnalizarUSU_SEQSER: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_CODSER: TStringField;
    ConsUsu_TSerMovAnalizarUSU_NUMCAD: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_CODDEP: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_QTDSER: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_PREUNI: TBCDField;
    ConsUsu_TSerMovAnalizarUSU_DATSER: TDateTimeField;
    ConsUsu_TSerMovAnalizarUSU_MESSER: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_ANOSER: TIntegerField;
    ConsUsu_TSerMovAnalizarUSU_NOMFUN: TStringField;
    ConsUsu_TSerMovAnalizarUSU_OBSSER: TStringField;
    ConsUsu_TSerMovAnalizarUSU_INADT: TStringField;
    ConsUsu_TSerMovAnalizarUSU_VLRCOB: TBCDField;
    RvConvenio_Analizar: TRvProject;
    RvConsUsu_TSerMovAnalizar: TRvDataSetConnection;
    ConsUsu_TSerMovAnalizarUSU_NOMFUN_1: TStringField;
    ConsUsu_TSerMovAdiantamentos: TADOQuery;
    ConsUsu_TSerMovAdiantamentosUSU_SEQSER: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_CODSER: TStringField;
    ConsUsu_TSerMovAdiantamentosUSU_NUMCAD: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_CODDEP: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_QTDSER: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_PREUNI: TBCDField;
    ConsUsu_TSerMovAdiantamentosUSU_DATSER: TDateTimeField;
    ConsUsu_TSerMovAdiantamentosUSU_MESSER: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_ANOSER: TIntegerField;
    ConsUsu_TSerMovAdiantamentosUSU_NOMFUN: TStringField;
    ConsUsu_TSerMovAdiantamentosUSU_OBSSER: TStringField;
    ConsUsu_TSerMovAdiantamentosUSU_INADT: TStringField;
    ConsUsu_TSerMovAdiantamentosUSU_VLRCOB: TBCDField;
    ConsUsu_TSerMovAdiantamentosUSU_NOMFUN_1: TStringField;
    RvConvenio_Adiantamentos: TRvProject;
    RvConsUsu_TSerMovAdiantamentos: TRvDataSetConnection;
    ConsUsu_TRhSerMovvnTotal: TFloatField;
    ConsAdtFuncRecibo: TADOQuery;
    ConsAdtFuncReciboUSU_NUMCAD: TIntegerField;
    ConsAdtFuncReciboUSU_NUMADT: TIntegerField;
    ConsAdtFuncReciboUSU_DATADT: TDateTimeField;
    ConsAdtFuncReciboUSU_VLRADT: TBCDField;
    ConsAdtFuncReciboUSU_VLRPAR: TBCDField;
    ConsAdtFuncReciboUSU_VLRPGT: TBCDField;
    ConsAdtFuncReciboUSU_VLRABE: TBCDField;
    ConsAdtFuncReciboUSU_DATVCT: TDateTimeField;
    ConsAdtFuncReciboUSU_SITADT: TStringField;
    ConsAdtFuncReciboUSU_DSCFLA: TStringField;
    ConsAdtFuncReciboUSU_DATMOV: TDateTimeField;
    ConsAdtFuncReciboUSU_SEQMOV: TIntegerField;
    ConsAdtFuncReciboUSU_SEQADT: TIntegerField;
    ConsAdtFuncReciboUSU_VLRDSC: TBCDField;
    ClientReciboAdt: TClientDataSet;
    ClientReciboAdtVlrPar: TFloatField;
    ClientReciboAdtVlrExt: TStringField;
    ClientReciboAdtDatVct: TDateField;
    ClientReciboAdtQtdPar: TIntegerField;
    ClientReciboAdtSeqPar: TIntegerField;
    RvReciboAdt: TRvProject;
    RvClientReciboAdt: TRvDataSetConnection;
    ConsAdtCobrarMes: TADOQuery;
    ConsAdtCobrarMesUSU_NOMFUN: TStringField;
    ConsAdtCobrarMesUSU_NUMCAD: TIntegerField;
    ConsAdtCobrarMesUSU_NUMADT: TIntegerField;
    ConsAdtCobrarMesUSU_DATADT: TDateTimeField;
    ConsAdtCobrarMesUSU_VLRADT: TBCDField;
    ConsAdtCobrarMesUSU_VLRPAR: TBCDField;
    ConsAdtCobrarMesUSU_VLRPGT: TBCDField;
    ConsAdtCobrarMesUSU_VLRABE: TBCDField;
    ConsAdtCobrarMesUSU_DATVCT: TDateTimeField;
    ConsAdtCobrarMesUSU_SITADT: TStringField;
    ConsAdtCobrarMesUSU_DSCFLA: TStringField;
    ConsAdtCobrarMesUSU_DATMOV: TDateTimeField;
    ConsAdtCobrarMesUSU_SEQMOV: TIntegerField;
    ConsAdtCobrarMesUSU_SEQADT: TIntegerField;
    ConsAdtCobrarMesUSU_VLRDSC: TBCDField;
    RvAdtCobrarMes: TRvProject;
    RvConsAdtCobrarMes: TRvDataSetConnection;
    ConsAdtCobrarMesQTDPAR: TFMTBCDField;
    ConsAdtDescFolhaMes: TADOQuery;
    ConsAdtDescFolhaMesUSU_NOMFUN: TStringField;
    ConsAdtDescFolhaMesUSU_NUMCAD: TIntegerField;
    ConsAdtDescFolhaMesUSU_NUMADT: TIntegerField;
    ConsAdtDescFolhaMesUSU_DATADT: TDateTimeField;
    ConsAdtDescFolhaMesUSU_VLRADT: TBCDField;
    ConsAdtDescFolhaMesUSU_VLRPAR: TBCDField;
    ConsAdtDescFolhaMesUSU_VLRPGT: TBCDField;
    ConsAdtDescFolhaMesUSU_VLRABE: TBCDField;
    ConsAdtDescFolhaMesUSU_DATVCT: TDateTimeField;
    ConsAdtDescFolhaMesUSU_SITADT: TStringField;
    ConsAdtDescFolhaMesUSU_DSCFLA: TStringField;
    ConsAdtDescFolhaMesUSU_DATMOV: TDateTimeField;
    ConsAdtDescFolhaMesUSU_SEQMOV: TIntegerField;
    ConsAdtDescFolhaMesUSU_SEQADT: TIntegerField;
    ConsAdtDescFolhaMesUSU_VLRDSC: TBCDField;
    ConsAdtDescFolhaMesQTDPAR: TFMTBCDField;
    RvAdtDescFolhaMes: TRvProject;
    RvConsAdtDescFolhaMes: TRvDataSetConnection;
    procedure ConsUsu_TRhFunAfterScroll(DataSet: TDataSet);
    procedure ConsUsu_TRhSerMovCalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  DmRave: TDmRave;

implementation

uses UDmOra, UConsFaturamento, UDm1, URelatoriosConvenio;

{$R *.dfm}

procedure TDmRave.ConsUsu_TRhFunAfterScroll(DataSet: TDataSet);
begin
    ConsUsu_TRhSerMov.Close;
    ConsUsu_TRhSerMov.Parameters.ParamByName('NUMCAD').Value := ConsUsu_TRhFunUSU_NUMCAD.Value;
    ConsUsu_TRhSerMov.Parameters.ParamByName('MESSER').Value := FRelatoriosConvenio.CbMes.ItemIndex;
    ConsUsu_TRhSerMov.Parameters.ParamByName('ANOSER').Value := StrToInt(FRelatoriosConvenio.EdAno.Text);
    ConsUsu_TRhSerMov.Open;

end;

procedure TDmRave.ConsUsu_TRhSerMovCalcFields(DataSet: TDataSet);
begin
    ConsUsu_TRhSerMovvnTotal.Value := ConsUsu_TRhSerMovUSU_QTDSER.Value * ConsUsu_TRhSerMovUSU_PREUNI.Value;
end;

end.
